export const locales = ['en', 'fr', 'zh']

/* Partner names are proper nouns shared across locales: [latin, chinese].
   Entries without a public latin name carry the Chinese mark only. */
/* [latin, zh, logo] — logos scraped from cnxili.com and xilixn.com partner walls. */
export const partnersList = [
  ['State Grid', '国家电网', 'state-grid'],
  ['China Southern Power Grid', '中国南方电网', 'southern-grid'],
  ['Tianneng Group', '天能控股集团', 'tianneng'],
  ['EVE Energy', '亿纬锂能', 'eve'],
  ['Ganfeng Lithium', '赣锋锂业', 'ganfeng'],
  ['Guoxuan High-Tech', '国轩高科', 'guoxuan'],
  ['AIMA', '爱玛', 'aima'],
  ['DFD New Energy', '多氟多新能源', 'dfd'],
  ['CB New Energy', '中比新能源', 'cb-new-energy'],
  ['TONLY', '台翔', 'tonly'],
  ['Today Sunshine', '今日阳光', 'today-sunshine'],
  ['SENUO', '赛诺', 'senuo'],
  ['Shansu', '闪速', 'shansu'],
  ['Chaoliyuan', '超力源', 'chaoliyuan'],
  ['GEYI Group', '格一集团', 'geyi'],
  ['ETSU', '艾越', 'etsu'],
  ['CPNN', '中国电力新闻网', 'cpnn'],
]


/* Real product catalogue for the power-intelligence line. Photos live in
   /assets/products; names keyed by locale code. */
export const meterCatalog = [
  {
    key: 'single-phase',
    title: { en: 'Single-phase smart meters', fr: 'Compteurs monophasés intelligents', zh: '单相智能电能表' },
    items: [
      { img: 'ddzy311', model: 'DDZY311', name: { en: 'Class-A single-phase smart payment meter (remote, built-in/external switch)', fr: 'Compteur monophasé intelligent classe A (télécommande, interrupteur intégré/externe)', zh: 'A级单相费控智能电能表（远程，开关内置/外置）' } },
      { img: 'ddz311', model: 'DDZ311', name: { en: 'Class-A single-phase smart payment meter (comms module, built-in/external switch)', fr: 'Compteur monophasé intelligent classe A (module de communication)', zh: 'A级单相费控智能电能表（通信模块，开关内置/外置）' } },
      { img: 'ddzm311', model: 'DDZM311', name: { en: 'Class-A single-phase smart gateway meter (comms module, built-in switch)', fr: 'Compteur passerelle monophasé intelligent classe A', zh: 'A级单相智能网关电能表系列（通信模块，开关内置）' } },
      { img: 'ddzy311-g', model: 'DDZY311-G', name: { en: 'Single-phase smart payment meter (remote, replaceable battery, wall-mount)', fr: 'Compteur monophasé intelligent (batterie remplaçable, mural)', zh: '单相费控智能电能表（远程，电池可换，壁挂式）' } },
      { img: 'ddsu311-2p', model: 'DDSU311', name: { en: 'Single-phase electronic energy meter (2P DIN-rail)', fr: 'Compteur monophasé électronique (rail DIN 2P)', zh: '单相电子式电能表系列（2P 导轨式）' } },
      { img: 'ddsu311-4p', model: 'DDSU311', name: { en: 'Single-phase smart payment meter (4P DIN-rail)', fr: 'Compteur monophasé intelligent (rail DIN 4P)', zh: '单相费控智能电能表系列（4P 导轨式）' } },
    ],
  },
  {
    key: 'three-phase',
    title: { en: 'Three-phase smart meters', fr: 'Compteurs triphasés intelligents', zh: '三相智能电能表' },
    items: [
      { img: 'dtzy311-b', model: 'DTZY311', name: { en: 'Class-B three-phase smart payment meter (remote, built-in/external switch)', fr: 'Compteur triphasé intelligent classe B (télécommande)', zh: 'B级三相费控智能电能表系列（远程，开关内置/外置）' } },
      { img: 'dtzy311-c', model: 'DTZY311', name: { en: 'Class-C three-phase smart payment meter (remote, built-in/external switch)', fr: 'Compteur triphasé intelligent classe C (télécommande)', zh: 'C级三相费控智能电能表系列（远程，开关内置/外置）' } },
      { img: 'dtz311', model: 'DTZ311', name: { en: 'Class-B three-phase smart meter (comms module, external switch)', fr: 'Compteur triphasé intelligent classe B (module de communication)', zh: 'B级三相智能电能表系列（通信模块，开关外置）' } },
      { img: 'dtzm311-g', model: 'DTZM311-G', name: { en: 'Three-phase four-wire smart gateway meter', fr: 'Compteur passerelle triphasé quatre fils', zh: '三相四线智能电能表（智能网关）' } },
      { img: 'dtzy311-d', model: 'DTZY311-D', name: { en: 'Three-phase four-wire smart payment meter', fr: 'Compteur triphasé quatre fils à prépaiement', zh: '三相四线费控智能电能表' } },
      { img: 'dtzy311-g', model: 'DTZY311-G / DSZY311-G', name: { en: 'Three-phase smart payment meter (wall-mount)', fr: 'Compteur triphasé intelligent (mural)', zh: '三相费控智能电能表系列（壁挂式）' } },
      { img: 'dtsu311', model: 'DTSU311 / DSSU311', name: { en: 'Three-phase electronic energy meter (DIN-rail)', fr: 'Compteur triphasé électronique (rail DIN)', zh: '三相电子式电能表系列（导轨式）' } },
    ],
  },
  {
    key: 'dc-meters',
    title: { en: 'DC energy meters', fr: "Compteurs d'énergie CC", zh: '直流电能表' },
    items: [
      { img: 'djs311', model: 'DJS311', name: { en: 'Static DC energy meter (panel-mount)', fr: "Compteur d'énergie CC statique (encastré)", zh: '静止式直流电能表系列（嵌入式）' } },
      { img: 'djsf311', model: 'DJSF311', name: { en: 'Static DC energy meter (wall-mount)', fr: "Compteur d'énergie CC statique (mural)", zh: '静止式直流电能表系列（壁挂式）' } },
      { img: 'djsu311', model: 'DJSU311', name: { en: 'Electronic DC energy meter (DIN-rail)', fr: 'Compteur CC électronique (rail DIN)', zh: '直流电子式电能表系列（导轨式）' } },
    ],
  },
  {
    key: 'water-meters',
    title: { en: 'Smart water meters', fr: "Compteurs d'eau intelligents", zh: '智能水表' },
    items: [
      { img: 'lxsg-z', model: 'LXSG-Z', name: { en: 'Direct-reading remote water meter', fr: "Compteur d'eau à télérelevé direct", zh: '直读式远传水表' } },
      { img: 'lxsg-zf', model: 'LXSG-ZF', name: { en: 'Direct-reading remote water meter with valve control', fr: "Compteur d'eau à télérelevé direct avec vanne pilotée", zh: '直读式远传阀控水表' } },
      { img: 'lxsy-wl', model: 'LXSY-WL', name: { en: 'Wireless smart remote water meter with valve control', fr: "Compteur d'eau intelligent sans fil avec vanne pilotée", zh: '无线智能远传阀控水表' } },
      { img: 'lxsy', model: 'LXSY', name: { en: 'Wireless remote smart water meter', fr: "Compteur d'eau intelligent à télérelevé sans fil", zh: '无线远传智能水表' } },
      { img: 'lxsk', model: 'LXSK', name: { en: 'RF-card prepaid water meter', fr: "Compteur d'eau prépayé à carte RF", zh: '射频卡预付费水表' } },
      { img: 'lxsy-nb', model: 'LXSY-NB', name: { en: 'NB-IoT remote water meter', fr: "Compteur d'eau à télérelevé NB-IoT", zh: 'NB-IoT 无线远传智能水表' } },
      { img: 'lxc-wlf', model: 'LXC-WLF', name: { en: 'LoRa ultrasonic water meter with valve control', fr: "Compteur d'eau ultrasonique LoRa avec vanne pilotée", zh: 'LoRa 无线远传阀控超声波水表' } },
      { img: 'lxc-wf', model: 'LXC-WF', name: { en: 'NB-IoT ultrasonic water meter with valve control', fr: "Compteur d'eau ultrasonique NB-IoT avec vanne pilotée", zh: 'NB-IoT 无线远传阀控超声波水表' } },
    ],
  },
  {
    key: 'terminals',
    title: { en: 'Acquisition terminals & gateways', fr: "Terminaux d'acquisition et passerelles", zh: '采集终端与网关' },
    items: [
      { img: 'ecu4h13', model: 'ECU4H13-XL31101', name: { en: 'Energy controller (dedicated transformer)', fr: "Contrôleur d'énergie (transformateur dédié)", zh: '能源控制器（专变）' } },
      { img: 'fkta43', model: 'FKTA43-XL31102', name: { en: 'Dedicated-transformer acquisition terminal (Type I)', fr: "Terminal d'acquisition (transformateur dédié, type I)", zh: '专变采集终端（I 型）' } },
      { img: 'ift-xl31101', model: 'IFT-XL31101', name: { en: 'Intelligent fusion terminal', fr: 'Terminal de fusion intelligent', zh: '智能融合终端' } },
      { img: 'wjtl33', model: 'WJTL33-XL31105I', name: { en: 'Concentrator (joint water–electricity reading)', fr: 'Concentrateur (relevé eau-électricité)', zh: '集中器（水电同抄）' } },
      { img: 'xlft-311', model: 'XLFT-311', name: { en: 'District smart fusion terminal', fr: 'Terminal de fusion intelligent de secteur', zh: '台区智能融合终端' } },
      { img: 'ecu4h23', model: 'ECU4H23-XL31101', name: { en: 'Energy controller', fr: "Contrôleur d'énergie", zh: '能源控制器' } },
      { img: 'djtl33', model: 'DJTL33-XL31109', name: { en: 'Concentrator Type II (4G public wireless)', fr: 'Concentrateur type II (réseau public 4G)', zh: '集中器Ⅱ型（无线公网 4G）' } },
      { img: 'djth23', model: 'DJTH23-XL31113', name: { en: 'Concentrator Type I (4G + HPLC dual-mode)', fr: 'Concentrateur type I (bimode 4G + HPLC)', zh: '集中器Ⅰ型（4G–HPLC 双模）' } },
    ],
  },
  {
    key: 'transformers',
    title: { en: 'Metering instrument transformers', fr: 'Transformateurs de mesure', zh: '计量用互感器' },
    items: [
      { img: 'lmz1d-xlp1', model: 'LMZ1D-XLP1', name: { en: 'Low-voltage metering current transformer — 0.66 kV, 75–150/5 A, class 0.2S/0.5S', fr: 'Transformateur de courant BT — 0,66 kV, 75–150/5 A, classe 0,2S/0,5S', zh: '计量用低压电流互感器 — 0.66kV，75–150/5A，0.2S/0.5S 级' } },
      { img: 'ljzn1-10', model: 'LJZN1-10', name: { en: '10–35 kV metering current transformer — 30–750/5 A, class 0.2S/0.5S', fr: 'Transformateur de courant 10–35 kV — 30–750/5 A, classe 0,2S/0,5S', zh: '10kV–35kV 计量用电流互感器 — 30–750/5A，0.2S/0.5S 级' } },
      { img: 'jdzqn-10', model: 'JDZQN-10', name: { en: '10–35 kV metering voltage transformer — 10/0.1 kV, class 0.2/0.5, single-phase', fr: 'Transformateur de tension 10–35 kV — 10/0,1 kV, classe 0,2/0,5, monophasé', zh: '10kV–35kV 计量用电压互感器 — 10/0.1kV，0.2/0.5 级，单相不接地' } },
      { img: 'jzzv1-10', model: 'JZZV1-10', name: { en: 'Metering combined transformer — V/V wiring, voltage class 0.2 / current class 0.2S', fr: 'Transformateur combiné de mesure — couplage V/V, classes 0,2 / 0,2S', zh: '计量用组合互感器 — V/V 接线，电压 0.2 级／电流 0.2S 级' } },
      { img: 'xls-005', model: 'XLS-005-N-15', name: { en: 'Three-phase current transformer', fr: 'Transformateur de courant triphasé', zh: '三相电流互感器' } },
      { img: 'xls-01s', model: 'XLS-01S-D-12', name: { en: 'Three-phase current transformer (split-core)', fr: 'Transformateur de courant triphasé (ouvrant)', zh: '三相电流互感器' } },
      { img: 'xld-02s', model: 'XLD-02S-N-25', name: { en: 'Single-phase neutral-line current transformer', fr: 'Transformateur de courant monophasé de neutre', zh: '单相零线电流互感器' } },
    ],
  },
  {
    key: 'modules',
    title: { en: 'Communication modules', fr: 'Modules de communication', zh: '通信模块' },
    items: [
      { img: 'dsm-nk', model: 'D-SM-NK-HZXL', name: { en: 'Dual-mode communication module (for single/three-phase meters)', fr: 'Module de communication bimode (compteurs)', zh: '双模通信模块（单三相电能表）' } },
      { img: 'jbd-sm-nk', model: 'JBD-SM-NK-HZXL', name: { en: 'Dual-mode communication module (for concentrators)', fr: 'Module bimode (concentrateurs)', zh: '双模通信模块（集中器）' } },
    ],
  },
  {
    key: 'distribution',
    title: { en: 'Distribution & metering enclosures', fr: 'Distribution et coffrets de comptage', zh: '配网产品与计量箱' },
    items: [
      { img: 'xlw-sxd2', model: 'XLW-SXD2', name: { en: 'IoT metering enclosure (distribution board)', fr: 'Coffret de comptage IoT (tableau de distribution)', zh: '物联网计量箱（配电板）' } },
      { img: 'xliem9l', model: 'XLIEM9L-250', name: { en: 'IoT smart moulded-case circuit breaker', fr: 'Disjoncteur intelligent IoT à boîtier moulé', zh: '物联智能断路器系列' } },
      { img: 'xlieb9l', model: 'XLIEB9L-80', name: { en: 'Smart-monitoring residual-current circuit breaker', fr: 'Disjoncteur différentiel à supervision intelligente', zh: '智能监控剩余电流动作断路器' } },
      { img: 'hxlb1n', model: 'HXLB1N-125Z', name: { en: 'External meter circuit breaker (isolating)', fr: 'Disjoncteur externe de compteur (sectionnement)', zh: '电能表外置断路器' } },
      { img: 'hxlb5n', model: 'HXLB5N-125Z', name: { en: 'External meter circuit breaker (residual-current)', fr: 'Disjoncteur externe de compteur (différentiel)', zh: '电能表外置断路器（剩余电流）' } },
      { img: 'cable-box-metal', model: 'XL-CB-M', name: { en: 'Cable branch box (metal enclosure)', fr: 'Coffret de dérivation câble (métal)', zh: '电缆分支箱（金属）' } },
      { img: 'cable-box-smc', model: 'XL-CB-SMC', name: { en: 'Cable branch box (SMC composite enclosure)', fr: 'Coffret de dérivation câble (composite SMC)', zh: '电缆分支箱（SMC 复合材料）' } },
    ],
  },
  {
    key: 'iot-eco',
    title: { en: 'Smart IoT ecosystem', fr: 'Écosystème IoT intelligent', zh: '智能物联生态' },
    items: [
      { img: 'xld-g', model: 'XLD-G-01', name: { en: 'Shared portable metering device', fr: 'Dispositif de comptage portable partagé', zh: '共享便携式计量装置' } },
      { img: 'xll-g', model: 'XLL-G-01', name: { en: 'Shared smart charging pillar', fr: 'Borne de recharge intelligente partagée', zh: '共享智能立柱' } },
      { img: 'xlc-tjd', model: 'XLC-TJD-01', name: { en: 'Smart socket (Tuya ecosystem)', fr: 'Prise intelligente (écosystème Tuya)', zh: '涂鸦生态智能插座' } },
      { img: 'xlk-t', model: 'XLK-TD/TS/TT-01', name: { en: 'Smart switch family (Tuya ecosystem)', fr: "Famille d'interrupteurs intelligents (écosystème Tuya)", zh: '涂鸦生态智能开关' } },
    ],
  },
]


/* Battery & new-energy catalogue (Zhejiang Xili New Energy, xilixn.com). */
export const batteryCatalog = [
  {
    key: 'power-series',
    title: { en: 'Power battery series', fr: 'Séries de batteries motrices', zh: '动力电池系列' },
    items: [
      { img: 'ne-weichi', model: '威驰 Weichi', name: { en: 'Power battery series engineered for electric two-wheelers', fr: 'Série de batteries motrices pour deux-roues électriques', zh: '"威驰"系列——专为二轮电动车研发设计' } },
      { img: 'ne-ruishi', model: '睿士 Ruishi', name: { en: 'Power battery series for light electric mobility', fr: 'Série de batteries pour mobilité électrique légère', zh: '"睿士"系列——轻型电动出行动力电池' } },
      { img: 'ne-puan', model: '浦安 Pu’an', name: { en: 'Power battery series for daily commuting', fr: 'Série de batteries pour les trajets du quotidien', zh: '"浦安"系列——日常通勤动力电池' } },
    ],
  },
  {
    key: 'xlf-models',
    title: { en: 'XLF swap battery models', fr: 'Modèles de batteries interchangeables XLF', zh: 'XLF 换电电池型号' },
    items: [
      { img: 'xlf3612t01', model: 'XLF3612T01', name: { en: '36 V / 12 Ah LFP battery, T-type case', fr: 'Batterie LFP 36 V / 12 Ah, boîtier T', zh: '36V/12Ah 磷酸铁锂电池（T 型壳）' } },
      { img: 'xlf4812t01', model: 'XLF4812T01', name: { en: '48 V / 12 Ah LFP battery, T-type case', fr: 'Batterie LFP 48 V / 12 Ah, boîtier T', zh: '48V/12Ah 磷酸铁锂电池（T 型壳）' } },
      { img: 'xlf4820p01', model: 'XLF4820P01', name: { en: '48 V / 20 Ah LFP battery, P-type case', fr: 'Batterie LFP 48 V / 20 Ah, boîtier P', zh: '48V/20Ah 磷酸铁锂电池（P 型壳）' } },
      { img: 'xlf4824t01', model: 'XLF4824T01', name: { en: '48 V / 24 Ah LFP battery, T-type case', fr: 'Batterie LFP 48 V / 24 Ah, boîtier T', zh: '48V/24Ah 磷酸铁锂电池（T 型壳）' } },
      { img: 'xlf4824p01', model: 'XLF4824P01', name: { en: '48 V / 24 Ah LFP battery, P-type case', fr: 'Batterie LFP 48 V / 24 Ah, boîtier P', zh: '48V/24Ah 磷酸铁锂电池（P 型壳）' } },
      { img: 'xlf4830p01', model: 'XLF4830P01', name: { en: '48 V / 30 Ah LFP battery, P-type case', fr: 'Batterie LFP 48 V / 30 Ah, boîtier P', zh: '48V/30Ah 磷酸铁锂电池（P 型壳）' } },
    ],
  },
]

export const content = {
  en: {
    locale: 'EN',
    code: 'en',
    meta: {
      title: 'Xili Technology — Energy intelligence',
      description: 'Smart energy intelligence, built on precision from measurement to resilient storage.',
    },
    common: {
      home: 'Home',
      explore: 'Explore',
      learnMore: 'Learn more',
      viewAll: 'View all',
      backTo: 'Back to',
      discuss: 'Discuss a solution',
      contactUs: 'Contact us',
      menu: 'Menu',
      close: 'Close menu',
      related: 'Related',
      keyPoints: 'Key capabilities',
      process: 'How we deliver',
      categories: 'Product lines',
      directions: 'Solution directions',
      scroll: 'Scroll',
      breadcrumbProducts: 'Products',
      breadcrumbSolutions: 'Solutions',
      imageSoon: 'Image coming soon',
      readMore: 'Read more',
    },
    nav: {
      products: 'Products',
      solutions: 'Solutions',
      technology: 'Technology',
      about: 'About us',
      news: 'News',
      careers: "We're hiring",
      contact: 'Contact',
    },
    marquee: ['Smart metering', 'Grid-edge data', 'Battery intelligence', 'Energy storage', 'Digital factory', 'Precision engineering'],
    home: {
      heroKicker: 'Quality first · Technology wins',
      heroTitle: 'Smart meters. Battery systems. Energy storage.',
      heroBody: 'Hangzhou Xili builds utility-grade electricity measurement and energy-storage systems — from grid-edge smart metering to commercial storage. Listed on the STAR Market since 2021.',
      heroPrimary: 'Explore products',
      heroSecondary: 'Meet Xili',
      stats: [
        [1968, '', 'Founded'],
        [2021, '', 'STAR Market listing'],
        [500, '+', 'Clients served'],
        [33, '', 'Provinces & regions covered'],
      ],
      pillarsIndex: 'Overview',
      pillarsTitle: 'One intelligence layer. Four essential capabilities.',
      pillarsBody: 'Xili connects electricity measurement, grid-edge data, battery intelligence and energy storage in one focused energy portfolio.',
      pillars: [
        ['01', 'Smart metering', 'Accurate electricity measurement at every point of the grid edge.'],
        ['02', 'Data acquisition', 'Connected visibility across electricity data and energy flows.'],
        ['03', 'Battery intelligence', 'Battery-management technology engineered for reliability.'],
        ['04', 'Energy storage', 'Distributed systems from portable power to commercial scale.'],
      ],
      productsIndex: 'Products',
      productsTitle: 'A portfolio built around the energy chain.',
      productsBody: 'Three product lines covering measurement, batteries and storage — each with its own dedicated overview.',
      solutionsIndex: 'Solutions',
      solutionsTitle: 'Systems that move energy forward.',
      solutionsBody: 'Five solution directions — grid, integrated energy, commercial, apartment and campus — connected by one precise energy language.',
      technologyIndex: 'Technology',
      technologyTitle: 'Precision is an operating system.',
      technologyBody: 'A digital factory connecting product lifecycle, manufacturing execution and data collection — from development to delivery.',
      technologyAction: 'Inside the digital factory',
      newsIndex: 'News',
      newsTitle: 'Latest from Xili.',
      partnersIndex: 'Cooperative partners',
      partnersTitle: 'Trusted across the energy chain.',
      partnersBody: 'Utilities, battery leaders and new-energy manufacturers Xili works alongside.',
      zhFirst: false,
      ctaTitle: 'Let’s make energy more legible.',
      ctaBody: 'Tell us where your energy system needs more precision, visibility or resilience.',
    },
    products: {
      title: 'Products',
      catalogIndex: 'Product catalogue',
      heroTitle: 'A portfolio built around the energy chain.',
      heroBody: 'From metering-grade measurement to batteries and storage — every product line is built on the same discipline: precision you can audit.',
      categories: [
        {
          slug: 'power-intelligence',
          name: 'Power intelligence',
          tagline: 'Measurement that the grid can trust.',
          description: 'Precision instruments for electricity measurement and grid-edge data visibility — the foundation of every downstream energy decision.',
          longText: 'From residential metering points to utility acquisition networks, Xili’s power-intelligence line turns raw electricity — and water — into structured, auditable data. Decades of metering heritage meet modern communications, smart distribution hardware and a growing IoT ecosystem.',
          items: [
            ['Smart meters', 'Single- and three-phase electricity metering engineered for accuracy classes demanded by modern grids.'],
            ['Smart water meters', 'Remote-reading, valve-control and ultrasonic water metering over NB-IoT and LoRa.'],
            ['Acquisition & distribution', 'Grid-edge terminals, concentrators, smart breakers and IoT metering enclosures at the point of supply.'],
          ],
          points: ['Metrology-grade accuracy', 'State Grid supplier rating: Grade A in every review since 2019', 'Utility-scale deployment', 'Connected communications'],
        },
        {
          slug: 'battery-systems',
          name: 'Battery systems',
          tagline: 'LFP cells, engineered for reliability.',
          description: 'Power batteries by Zhejiang Xili New Energy — LFP chemistry, steel-shell full-tab cells and full-domain BMS monitoring.',
          longText: 'Zhejiang Xili New Energy, founded in 2023 in the Moganshan National High-tech Zone, develops power batteries around four cell disciplines: safety (wide-temperature LFP), fast charge (1–3C, up to 5C), high energy density (170 Wh/kg) and long cycle life (2,000–2,500 cycles). Production runs on 70+ automatic injection machines, six SMT lines and automated PACK lines, with an MES system tracking quality across the full product life.',
          items: [
            ['Power batteries', 'LFP steel-shell cells with full-tab design — low internal resistance, strong heat dissipation, no swelling or cracking.'],
            ['Cell technology', 'Four R&D pillars: safety, 1–3C fast charge, 170 Wh/kg energy density, 2,000–2,500-cycle life.'],
            ['BMS intelligence', 'Full-domain monitoring; RS485/CAN/UART and one-wire protocols; IoT/NB-IoT with Bluetooth, WiFi, GPS and BeiDou.'],
          ],
          points: ['LFP chemistry, wide temperature range', '170 Wh/kg energy density', '2,000–2,500 cycle life'],
        },
        {
          slug: 'energy-storage',
          name: 'Energy storage',
          tagline: 'Resilience at every scale.',
          description: 'Storage systems spanning portable, residential and commercial applications.',
          longText: 'From portable power stations to home and commercial installations, the storage line extends Xili’s measurement and battery expertise into complete energy systems that store, shift and secure electricity.',
          items: [
            ['Portable power stations', 'Mobile LFP energy — e.g. 1,152 Wh / 48 V at 9 kg, 1,500 cycles above 70% capacity.'],
            ['Home energy storage', 'Residential systems that pair with rooftop PV for self-consumption and backup.'],
            ['Commercial energy storage', 'Scalable systems for industrial and commercial energy management.'],
          ],
          points: ['IP67 waterproof · V0 flame-retardant', 'Smart BMS with full-domain monitoring', 'Digital platform — PC and mobile'],
        },
      ],
    },
    solutions: {
      title: 'Solutions',
      heroTitle: 'Systems that move energy forward.',
      heroBody: 'Five solution directions — grid, integrated energy, commercial, apartment and campus — connected by one precise energy language.',
      items: [
        {
          slug: 'grid-intelligence',
          name: 'Grid intelligence',
          tagline: 'A more visible grid edge.',
          description: 'Smart metering, electricity-data acquisition and energy metering systems for utilities and grid operators.',
          longText: 'Grid intelligence starts at the measurement point. Xili combines smart meters, acquisition terminals and metering-box systems into deployments that give operators an accurate, continuous view of the grid edge.',
          points: [
            ['Accurate measurement', 'Metering products engineered to the accuracy classes utility programmes demand.'],
            ['Connected acquisition', 'Terminals and concentrators that move electricity data reliably into utility systems.'],
            ['Deployment experience', 'A metering heritage measured in decades, applied to modern rollout programmes.'],
          ],
          steps: ['Assess the metering landscape', 'Configure products and communications', 'Deploy and verify at scale', 'Support the installed base'],
        },
        {
          slug: 'pv-storage-charging',
          name: 'PV · Storage · Charging',
          tagline: 'One integrated energy loop.',
          description: 'A documented integrated direction for photovoltaic generation, energy storage and charging.',
          longText: 'Generation, storage and charging are one system, not three. This direction integrates PV input, battery storage and charging loads under coherent measurement and control — so energy flows where it is needed, when it is worth most.',
          points: [
            ['Generation-aware storage', 'Storage sized and controlled around real PV production profiles.'],
            ['Charging integration', 'Charging loads managed as part of the energy loop, not an afterthought.'],
            ['Measured everywhere', 'Xili metering discipline applied across every flow in the system.'],
          ],
          steps: ['Profile generation and loads', 'Design the integrated system', 'Install and commission', 'Operate with full visibility'],
        },
        {
          slug: 'commercial-energy',
          name: 'Commercial energy management',
          tagline: 'Energy as an operating advantage.',
          description: 'An integrated energy-management direction for industrial and commercial needs.',
          longText: 'For industrial and commercial sites, energy is a controllable cost and a resilience question. This direction combines measurement, storage and management so operators can see consumption clearly and act on it confidently. Deployed today in technology parks, office buildings, enterprises and shopping complexes: access, electricity and water read and controlled from one console, WeChat and app clients for balance top-up and fault reporting, and a cloud platform open to multi-party integration.',
          points: [
            ['Visibility first', 'Granular measurement across feeders, loads and time.'],
            ['Storage where it pays', 'Commercial storage applied to peak, backup and self-consumption value.'],
            ['Management in one loop', 'Data, storage and control working as one system.'],
          ],
          steps: ['Audit energy flows', 'Model the value case', 'Deploy measurement and storage', 'Manage and optimise'],
        },
        {
          slug: 'apartment-energy',
          name: 'Apartment energy management',
          tagline: 'Rental housing, running on one platform.',
          description: 'A smart hardware-and-software system for centralised, distributed and co-living apartments — contracts, rent and utilities managed in one place.',
          longText: 'The apartment solution gives operators one console for the whole rental business: contracts, rent and agency property services alongside smart devices — door locks, electricity, water and gas — with automated reading, statistics, remote control and resident announcements. Tenants use the app or WeChat client to check and top up rent and utilities, unlock doors remotely and report faults. The cloud platform stays open for multi-party integration across the smart-apartment ecosystem.',
          points: [
            ['One operator console', 'Contracts, rent, property services and smart-device data — read, counted and controlled in one place.'],
            ['A tenant app that answers', 'Rent and utility balances, top-ups, remote door locks, hardware control and one-tap fault reporting.'],
            ['An open cloud platform', 'Multi-party integration for the apartment ecosystem — operators, owners and service partners.'],
          ],
          steps: ['Survey the rental portfolio', 'Install smart locks, meters and sensors', 'Connect the console and tenant apps', 'Operate, settle and grow'],
        },
        {
          slug: 'campus-energy',
          name: 'Campus energy management',
          tagline: 'Utilities on campus, clearly managed.',
          description: 'An integrated water-and-electricity management solution for schools and campuses — smart hardware, IoT communications, cloud platform and mobile clients in one system.',
          longText: 'Built on Xili’s own smart meters, water meters and concentrators, the campus solution gives administrators one platform for both utilities: remote reading and remote valve or switch control, prepaid billing with automatic reminders, and safety policies such as scheduled power windows and overload protection for dormitories and teaching buildings.',
          points: [
            ['Remote reading & control', 'Electricity and water read remotely on one platform, with remote switch and valve control by room or building.'],
            ['Prepaid & automated billing', 'Prepaid accounts, automatic low-balance reminders and clear settlement for every dormitory.'],
            ['Safety by policy', 'Scheduled supply windows, overload and malicious-load protection designed for student housing.'],
          ],
          steps: ['Survey campus water and power', 'Deploy smart meters and concentrators', 'Connect the cloud platform and apps', 'Operate, bill and optimise'],
        },
      ],
    },
    technology: {
      title: 'Technology',
      heroTitle: 'Precision is an operating system.',
      heroBody: 'Xili’s digital factory connects product lifecycle, manufacturing execution, equipment and data-collection systems across the path from development to delivery.',
      sectionTitle: 'The digital factory',
      sectionBody: 'Since 2005, Xili has built manufacturing around connected systems — so that quality is measured, not assumed.',
      list: [
        ['Smart-meter engineering', 'Metrology-grade design and verification, from circuit to calibration.'],
        ['BMS & communications', 'Battery management and the connected protocols that carry energy data.'],
        ['Digital factory systems', 'PLM, MES and equipment data joined in one manufacturing loop.'],
        ['Integrated testing', 'Automated inspection from production line to laboratory.'],
      ],
      note: 'Built for reliable deployment across modern energy infrastructure.',
      twinIndex: 'Digital twin',
      twinTitle: 'The factory, mirrored in data.',
      twinBody: 'Lines, warehousing and test benches feed one live digital model of the plant — the same telemetry that drives MES scheduling renders the hall as a living twin, where every machine can be watched, simulated and improved.',
      twinTags: ['SMT & assembly lines', 'Automated verification', 'AS/RS warehouse', 'AGV logistics'],
      aiIndex: 'AI & intelligence',
      aiTitle: 'AI works the line beside us.',
      aiBody: 'Xili’s AI-and-manufacturing integration was selected as a provincial and national model case. Intelligence is not a pilot project here — it is embedded in inspection, scheduling and everyday operations.',
      aiList: [
        ['Large-model applications', 'AI large models embedded in quality analytics, production knowledge and operations workflows — answers drawn from the factory’s own data.'],
        ['Machine-vision inspection', 'Vision systems inspect boards and assemblies inline, catching defects at line speed before they travel downstream.'],
        ['AI-assisted scheduling', 'Algorithms plan across 34 lines and 270+ machines, balancing tender deadlines against capacity in the MES.'],
        ['Digital operations platform', 'Company-wide operations rendered visual and data-driven — live since 2024, from order to delivery.'],
      ],
      labsIndex: 'Laboratories',
      labsTitle: 'Automated laboratories, around the clock.',
      labsBody: 'Verification does not wait for a shift. Xili’s testing centre — accredited by CNAS, the China National Accreditation Service for Conformity Assessment — runs automated benches that calibrate, stress and certify products continuously. That discipline is why Xili has passed national and provincial quality supervision checks for twenty consecutive years.',
      labsList: [
        ['Automated verification & calibration', 'Robotic benches verify meters against reference standards — high-volume, operator-light, audit-ready.'],
        ['Reliability & environmental testing', 'Temperature, humidity, surge and life-cycle chambers prove products against years of field stress.'],
        ['EMC & electrical safety', 'Electromagnetic-compatibility and safety benches qualify products for grid environments and export markets.'],
        ['Battery & new-energy testing', 'Cell and pack benches cycle, load and abuse-test LFP batteries across the full temperature window.'],
      ],
      ipIndex: 'Standards & IP',
      ipTitle: 'Written into the standards.',
      ipStats: [
        [132, '', 'Patents granted'],
        [27, '', 'Invention patents'],
        [148, '', 'Software copyrights'],
        [42, '', 'National, industry & group standards co-drafted'],
      ],
      ipNote: 'Recognition includes the China Patent Excellence Award (2018), the China Invention & Entrepreneurship Achievement Award, second class (2025), and selection of the DJTD23-XL31102 concentrator as a 2025 “Made in Zhejiang” premium product.',
      milestonesTitle: 'Engineering milestones',
      milestones: [
        ['2005', 'Digital factory journey', 'Manufacturing execution and product lifecycle systems come online.'],
        ['2023', 'Deqing park in production', 'Digital workshops and automated warehousing across a 120,000 m² intelligent park.'],
        ['2025', 'AI-enabled manufacturing', 'Deep AI-manufacturing integration, selected as a provincial and national model case.'],
      ],
    },
    about: {
      title: 'About us',
      heroTitle: 'From a four-person pump station to the STAR Market.',
      heroBody: 'In 1968, Xili began as a three-to-four-person irrigation pump station of the West Lake Agricultural Machinery Factory. In 2021 it became the first STAR-Market-listed company in the smart-meter industry.',
      storyTitle: 'Fifty-seven years, one conviction',
      storyBody: '“Quality as the foundation, technology as the winning edge” has carried Xili through nearly six decades — from mechanical meters to smart meters, from traditional manufacturing to AI-enabled production. Restructured as a private company in 1999, past the hundred-million-yuan revenue mark in 2010, listed on the STAR Market in 2021, and now running a 120,000 m² intelligent industrial park in Deqing. Today Xili operates 34 production lines with 270+ pieces of production and test equipment, serves 500+ clients across 33 Chinese provinces, and exports to markets including Thailand, Bangladesh, Korea, the Philippines, Ghana, Chile, Ecuador and Pakistan — with products passing national and provincial quality supervision checks for twenty consecutive years.',
      globalIndex: 'Global footprint',
      globalTitle: 'Measured at home. Trusted abroad.',
      globalBody: 'Xili serves 500+ clients across all 33 provincial-level regions of China, and ships metering products to export markets across Southeast Asia, Africa, Eastern Europe and South America. The company is a member of the DLMS User Association (Switzerland) and the STS Association (South Africa) — the two standards bodies that govern how the world’s meters communicate and prepay.',
      globalHub: 'Hangzhou',
      globalMarkets: ['Thailand', 'Bangladesh', 'South Korea', 'Philippines', 'Eastern Europe', 'Ghana', 'Chile', 'Ecuador', 'Pakistan'],
      globalStats: [
        [33, '', 'Provinces & regions in China'],
        [10, '', 'Export markets'],
        [24, '', 'Long-term partners'],
      ],
      investorIndex: 'Investor relations',
      investorTitle: 'Listed. Audited. Dividend-paying.',
      investorStats: [
        ['¥566M', 'Revenue · FY2025'],
        ['¥104M', 'Net profit · FY2025'],
        ['5.5%', 'Of revenue into R&D'],
        ['50.9%', 'Dividend payout ratio'],
      ],
      investorNote: 'Hangzhou Xili Intelligent Technology Co., Ltd. — 688616.SH, STAR Market, Shanghai Stock Exchange. Audited by Pan-China CPAs with an unqualified opinion. Investor relations: zqb@cnxili.com',
      valuesTitle: 'Corporate culture',
      values: [
        ['Heritage & drive', 'Fifty-seven years from a pump station to a listed technology company — the founding grit remains.'],
        ['Quality first, technology wins', 'Reverence for quality and persistence in technology power every leap we make.'],
        ['Grow together, share together', 'Institutional, process-driven management — and a career path for every builder on the team.'],
      ],
      timelineTitle: 'Milestones',
      timeline: [
        ['1968', 'Founded', 'Started as a 3–4 person irrigation pump station of the West Lake Agricultural Machinery Factory.'],
        ['1999', 'Privatised', 'Shareholding reform completed; renamed Hangzhou Xili Electric Energy Meter Manufacturing.'],
        ['2010', '¥100M revenue', 'Annual revenue passed one hundred million yuan after strong State Grid tender results.'],
        ['2016', 'Joint-stock reform', 'Renamed Hangzhou Xili Intelligent Technology Co., Ltd.; modern governance in place.'],
        ['2021', 'STAR Market listing', 'Listed on 18 March 2021 (688616) — first listed company in the smart-meter industry on the STAR Market.'],
        ['2023', 'Deqing park online', 'The 120,000 m² intelligent industrial park entered full production with digital workshops and automated warehousing.'],
        ['2024', 'Record results', 'Net profit reached a record ¥104 million; digital operations platform went live.'],
        ['2025', 'AI in manufacturing', 'AI-manufacturing integration selected as a provincial and national model case; new-energy revenue up 281% year on year.'],
      ],
      honorsTitle: 'Honors & qualifications',
      honorStats: [
        [132, '', 'Patents granted'],
        [148, '', 'Software copyrights'],
        [42, '', 'Standards co-drafted'],
        [40, '+', 'Certified S&T achievements'],
      ],
      honors: [
        'State Grid supplier rating: Grade A in every review since 2019',
        'CNAS-accredited testing centre',
        'Member, DLMS User Association · STS Association',
        'National Green & Low-Carbon Factory',
        'National Intellectual Property Demonstration Enterprise',
        'National specialised & innovative SME (Zhejiang Xili)',
        'Provincial Key Enterprise Research Institute (2025)',
        'China Patent Excellence Award (2018)',
        'First STAR-Market-listed smart-meter company',
      ],
      csrTitle: 'Responsibility',
      csr: [
        ['Green, low-carbon manufacturing', 'Green process upgrades since 2014, with provincial environmental innovation awards; ongoing carbon verification and footprint certification in support of dual-carbon goals.'],
        ['Accountable governance', 'Quality, environment, occupational health & safety and information-security management systems — with an annual ESG report disclosing practice and performance.'],
        ['Community & care', 'A dedicated charity fund has supported 55 patients with ¥225,400 in aid by 2025, alongside pandemic-relief donations and staff blood-donation drives.'],
      ],
      officialAction: 'Official Xili Technology site',
      officialUrl: 'https://www.cnxili.com/en/WestForceProfile/index.aspx',
    },
    news: {
      title: 'News',
      heroTitle: 'News & milestones.',
      heroBody: 'Company announcements and the milestones that shaped Xili — updated as the story continues.',
      items: [
        ['2026', 'Contracts', 'State Grid tender wins exceed ¥162 million', 'Xili was named a winning bidder in State Grid’s 2026 first metering-equipment tender — Class-A single-phase and Class-B/C three-phase smart meters, smart fusion terminals and metering instrument transformers — worth ¥162 million in total, with further wins in Hubei, Anhui, Heilongjiang and Shanghai.', 'meter-line'],
        ['2026', 'ESG', '2025 ESG reports published', 'Hangzhou Xili and Zhejiang Xili published their 2025 environmental, social and governance reports, extending disclosure across both the metering and new-energy businesses.', 'pv-solution'],
        ['2026', 'Results', 'FY2025: steady profit and a ¥52.9M dividend', 'Revenue of ¥566 million with net profit of ¥104 million and operating cash flow up 53%. A ¥3-per-10-shares dividend returns 50.9% of net profit to shareholders.', 'zhuantang-hq'],
        ['2026', 'Manufacturing', 'Future-factory upgrade selected as a Zhejiang demonstration project', 'The smart energy-metering terminal future-factory retrofit was selected for Zhejiang Province’s 2026 production-mode transformation demonstration list.', 'robot-cell'],
        ['2026', 'Recognition', 'Named a national-level Green & Low-Carbon Factory', 'Xili Technology was awarded the national Green & Low-Carbon Factory designation, recognising energy-efficient, low-emission manufacturing across its parks.', 'deqing-park'],
        ['2025', 'Milestone', 'AI-manufacturing integration named a national model case', 'Xili’s deep integration of AI and manufacturing was selected as a provincial and national model case; Xili New Energy revenue grew 281% year on year.', 'robot-glow'],
        ['2024', 'Results', 'Record net profit of ¥104 million', 'Full-year net profit reached a record ¥104 million; the digital operations platform went live, bringing visual, data-driven management across the company.', 'hall'],
        ['2024', 'Certification', 'UN ECE certification for vehicle components', 'Zhejiang Xili New Energy obtains UN ECE conformity-of-production certificate E57*COP*1169, issued by the Republic of San Marino Authority for Homologation — series production of vehicle components recognised across the 56 member states of the UN 1958 Agreement.', 'doc-unece-cert'],
        ['2023', 'Manufacturing', 'Deqing intelligent industrial park in full production', 'The 120,000 m² park entered full production, with digital workshops and automated warehousing online.', 'campus-aerial'],
        ['2021', 'Milestone', 'Xili Technology lists on the STAR Market', 'Hangzhou Xili Intelligent Technology (688616.SH) lists on the STAR Market of the Shanghai Stock Exchange — a public commitment to precision engineering.', 'listing-2021'],
        ['2005', 'Manufacturing', 'The digital factory journey begins', 'Xili connects product lifecycle, manufacturing execution and equipment data into one loop — quality measured, not assumed.', 'factory-2005'],
        ['1968', 'Heritage', 'The metering heritage begins', 'The industrial foundation in electricity metering that still anchors Xili’s accuracy culture today.', 'heritage-1968'],
      ],
      note: 'Further announcements are published after official verification.',
    },
    careers: {
      title: 'Careers',
      heroTitle: 'Build the instruments the grid relies on.',
      heroBody: 'Precision work needs precise people. Join a team where measurement is a craft and energy is the mission.',
      whyTitle: 'Why Xili',
      why: [
        ['Real infrastructure', 'Your work ships into grids, factories and homes — measured in decades, not sprints.'],
        ['Engineering depth', 'Metrology, BMS, communications and manufacturing systems under one roof.'],
        ['A listed platform', 'The stability of a STAR-Market-listed company with the focus of a specialist.'],
      ],
      areasTitle: 'Hiring directions',
      areas: [
        ['R&D engineering', 'Metering, BMS, embedded and communications engineering.'],
        ['Manufacturing & supply chain', 'Digital-factory operations, process and equipment engineering.'],
        ['Quality & testing', 'Metrology-grade verification from line to laboratory.'],
        ['Market & sales', 'Utility programmes and international market development.'],
      ],
      action: 'Introduce yourself',
      note: 'Send your CV and the direction you’re interested in — we reply to every serious application.',
    },
    contact: {
      title: 'Contact',
      heroTitle: 'Let’s make energy more legible.',
      heroBody: 'Tell us where your energy system needs more precision, visibility or resilience.',
      action: 'Start a conversation',
      channelsTitle: 'Reach us',
      email: 'xenergy@cnxili.com',
      offices: 'Hangzhou · Deqing · China',
      officeTitle: 'Locations',
      locations: [
        ['zhuantang-hq', 'Hangzhou · Zhuantang', 'Xili Technology headquarters'],
        ['deqing-park', 'Huzhou · Deqing', 'Deqing intelligent industrial park'],
      ],
      emailTitle: 'Email',
      responseNote: 'We reply to solution enquiries within two business days.',
    },
    footer: {
      descriptor: 'Smart energy intelligence',
      colProducts: 'Products',
      colSolutions: 'Solutions',
      colCompany: 'Company',
      legal: '© 2026 Xili Technology. All rights reserved.',
    },
  },

  fr: {
    locale: 'FR',
    code: 'fr',
    meta: {
      title: 'Xili Technology — Intelligence énergétique',
      description: 'Une intelligence énergétique fondée sur la précision, de la mesure jusqu’au stockage résilient.',
    },
    common: {
      home: 'Accueil',
      explore: 'Explorer',
      learnMore: 'En savoir plus',
      viewAll: 'Tout voir',
      backTo: 'Retour à',
      discuss: 'Échanger sur une solution',
      contactUs: 'Nous contacter',
      menu: 'Menu',
      close: 'Fermer le menu',
      related: 'À découvrir',
      keyPoints: 'Capacités clés',
      process: 'Notre démarche',
      categories: 'Lignes de produits',
      directions: 'Orientations de solution',
      scroll: 'Défiler',
      breadcrumbProducts: 'Produits',
      breadcrumbSolutions: 'Solutions',
      imageSoon: 'Visuel à venir',
      readMore: 'Lire la suite',
    },
    nav: {
      products: 'Produits',
      solutions: 'Solutions',
      technology: 'Technologie',
      about: 'À propos',
      news: 'Actualités',
      careers: 'Nous recrutons',
      contact: 'Contact',
    },
    marquee: ['Comptage intelligent', 'Données de réseau', 'Intelligence batterie', 'Stockage d’énergie', 'Usine numérique', 'Ingénierie de précision'],
    home: {
      heroKicker: 'La qualité d’abord · La technologie l’emporte',
      heroTitle: 'Compteurs intelligents. Batteries. Stockage d’énergie.',
      heroBody: 'Hangzhou Xili conçoit des systèmes de mesure électrique et de stockage de qualité réseau — du comptage intelligent au stockage commercial. Cotée au STAR Market depuis 2021.',
      heroPrimary: 'Explorer les produits',
      heroSecondary: 'Découvrir Xili',
      stats: [
        [1968, '', 'Fondation'],
        [2021, '', 'Cotation au STAR Market'],
        [500, '+', 'Clients servis'],
        [33, '', 'Provinces et régions couvertes'],
      ],
      pillarsIndex: 'Présentation',
      pillarsTitle: 'Une seule couche d’intelligence. Quatre capacités essentielles.',
      pillarsBody: 'Xili réunit mesure électrique, données de réseau, intelligence batterie et stockage dans un portefeuille énergétique cohérent.',
      pillars: [
        ['01', 'Comptage intelligent', 'Une mesure électrique précise à chaque point du réseau.'],
        ['02', 'Acquisition de données', 'Une visibilité connectée sur les données et flux d’énergie.'],
        ['03', 'Intelligence batterie', 'Une technologie de gestion batterie conçue pour la fiabilité.'],
        ['04', 'Stockage d’énergie', 'Des systèmes distribués, du portable à l’échelle commerciale.'],
      ],
      productsIndex: 'Produits',
      productsTitle: 'Un portefeuille construit autour de la chaîne énergétique.',
      productsBody: 'Trois lignes de produits couvrant la mesure, les batteries et le stockage — chacune avec sa propre présentation.',
      solutionsIndex: 'Solutions',
      solutionsTitle: 'Des systèmes qui font avancer l’énergie.',
      solutionsBody: 'Cinq orientations de solution — réseau, énergie intégrée, commercial, résidentiel locatif et campus — connectées par un langage énergétique précis.',
      technologyIndex: 'Technologie',
      technologyTitle: 'La précision est un système d’exploitation.',
      technologyBody: 'Une usine numérique reliant cycle de vie produit, exécution de fabrication et collecte de données — du développement à la livraison.',
      technologyAction: 'Au cœur de l’usine numérique',
      newsIndex: 'Actualités',
      newsTitle: 'Dernières nouvelles de Xili.',
      partnersIndex: 'Partenaires',
      partnersTitle: 'La confiance de toute la chaîne énergétique.',
      partnersBody: 'Gestionnaires de réseau, leaders de la batterie et industriels des énergies nouvelles aux côtés de Xili.',
      zhFirst: false,
      ctaTitle: 'Rendons l’énergie plus lisible.',
      ctaBody: 'Indiquez-nous où votre système énergétique a besoin de plus de précision, de visibilité ou de résilience.',
    },
    products: {
      title: 'Produits',
      catalogIndex: 'Catalogue produits',
      heroTitle: 'Un portefeuille construit autour de la chaîne énergétique.',
      heroBody: 'De la mesure métrologique aux batteries et au stockage — chaque ligne de produits repose sur la même discipline : une précision vérifiable.',
      categories: [
        {
          slug: 'power-intelligence',
          name: 'Intelligence électrique',
          tagline: 'Une mesure digne de confiance pour le réseau.',
          description: 'Des instruments de précision pour la mesure électrique et la visibilité des données de réseau — le socle de toute décision énergétique.',
          longText: 'Du point de comptage résidentiel aux réseaux d’acquisition des distributeurs, la ligne intelligence électrique de Xili transforme l’électricité — et l’eau — en données structurées et vérifiables. Des décennies d’expérience du comptage rencontrent les communications modernes, le matériel de distribution intelligent et un écosystème IoT grandissant.',
          items: [
            ['Compteurs intelligents', 'Comptage mono- et triphasé conçu pour les classes de précision des réseaux modernes.'],
            ['Compteurs d’eau intelligents', 'Télérelevé, vannes pilotées et comptage ultrasonique sur NB-IoT et LoRa.'],
            ['Acquisition et distribution', 'Terminaux, concentrateurs, disjoncteurs intelligents et coffrets de comptage IoT au point de livraison.'],
          ],
          points: ['Précision métrologique', 'Fournisseur State Grid : classe A à chaque évaluation depuis 2019', 'Déploiement à grande échelle', 'Communications connectées'],
        },
        {
          slug: 'battery-systems',
          name: 'Systèmes batterie',
          tagline: 'Cellules LFP, conçues pour la fiabilité.',
          description: 'Batteries motrices de Zhejiang Xili New Energy — chimie LFP, cellules acier à languettes intégrales, BMS à supervision globale.',
          longText: 'Fondée en 2023 dans la zone high-tech nationale de Moganshan, Zhejiang Xili New Energy développe ses batteries autour de quatre disciplines : sécurité (LFP large plage de température), charge rapide (1–3C, jusqu’à 5C), densité énergétique élevée (170 Wh/kg) et longue durée de vie (2 000–2 500 cycles). La production s’appuie sur plus de 70 machines d’injection automatiques, six lignes SMT et des lignes PACK automatisées, avec un système MES de traçabilité qualité.',
          items: [
            ['Batteries motrices', 'Cellules LFP en boîtier acier à languettes intégrales — faible résistance interne, excellente dissipation, ni gonflement ni fissure.'],
            ['Technologie cellule', 'Quatre piliers R&D : sécurité, charge rapide 1–3C, 170 Wh/kg, 2 000–2 500 cycles.'],
            ['Intelligence BMS', 'Supervision globale ; protocoles RS485/CAN/UART et un fil ; IoT/NB-IoT avec Bluetooth, WiFi, GPS et BeiDou.'],
          ],
          points: ['Chimie LFP, large plage de température', 'Densité de 170 Wh/kg', '2 000–2 500 cycles de vie'],
        },
        {
          slug: 'energy-storage',
          name: 'Stockage d’énergie',
          tagline: 'La résilience à toutes les échelles.',
          description: 'Des systèmes de stockage portables, résidentiels et commerciaux.',
          longText: 'Des stations portables aux installations résidentielles et commerciales, la ligne stockage prolonge l’expertise de Xili en mesure et en batteries vers des systèmes complets qui stockent, déplacent et sécurisent l’électricité.',
          items: [
            ['Stations d’énergie portables', 'Énergie LFP mobile — p. ex. 1 152 Wh / 48 V pour 9 kg, 1 500 cycles au-dessus de 70 % de capacité.'],
            ['Stockage résidentiel', 'Des systèmes associés au PV en toiture pour l’autoconsommation et le secours.'],
            ['Stockage commercial', 'Des systèmes évolutifs pour la gestion énergétique industrielle et commerciale.'],
          ],
          points: ['Étanchéité IP67 · ignifugation V0', 'BMS intelligent à supervision globale', 'Plateforme numérique — PC et mobile'],
        },
      ],
    },
    solutions: {
      title: 'Solutions',
      heroTitle: 'Des systèmes qui font avancer l’énergie.',
      heroBody: 'Cinq orientations de solution — réseau, énergie intégrée, commercial, résidentiel locatif et campus — connectées par un langage énergétique précis.',
      items: [
        {
          slug: 'grid-intelligence',
          name: 'Intelligence réseau',
          tagline: 'Un réseau plus visible.',
          description: 'Comptage intelligent, acquisition de données et systèmes de mesure pour les gestionnaires de réseau.',
          longText: 'L’intelligence réseau commence au point de mesure. Xili combine compteurs, terminaux d’acquisition et coffrets de comptage en déploiements qui donnent aux opérateurs une vision précise et continue du réseau.',
          points: [
            ['Mesure précise', 'Des produits de comptage conçus pour les classes de précision exigées.'],
            ['Acquisition connectée', 'Des terminaux qui acheminent les données de façon fiable.'],
            ['Expérience de déploiement', 'Des décennies de comptage appliquées aux programmes modernes.'],
          ],
          steps: ['Évaluer le parc de comptage', 'Configurer produits et communications', 'Déployer et vérifier à l’échelle', 'Accompagner le parc installé'],
        },
        {
          slug: 'pv-storage-charging',
          name: 'PV · Stockage · Recharge',
          tagline: 'Une seule boucle énergétique.',
          description: 'Une orientation intégrée documentée pour le photovoltaïque, le stockage et la recharge.',
          longText: 'Production, stockage et recharge forment un seul système. Cette orientation intègre l’apport PV, le stockage batterie et les charges de recharge sous une mesure et un contrôle cohérents.',
          points: [
            ['Stockage lié à la production', 'Un stockage dimensionné sur les profils réels de production PV.'],
            ['Recharge intégrée', 'Des charges gérées comme partie de la boucle énergétique.'],
            ['Tout est mesuré', 'La discipline de comptage Xili appliquée à chaque flux.'],
          ],
          steps: ['Profiler production et charges', 'Concevoir le système intégré', 'Installer et mettre en service', 'Exploiter en pleine visibilité'],
        },
        {
          slug: 'commercial-energy',
          name: 'Gestion énergétique commerciale',
          tagline: 'L’énergie comme avantage opérationnel.',
          description: 'Une orientation de gestion énergétique intégrée pour les besoins industriels et commerciaux.',
          longText: 'Pour les sites industriels et commerciaux, l’énergie est un coût pilotable et une question de résilience. Cette orientation combine mesure, stockage et gestion pour agir en confiance. Déployée aujourd’hui dans les parcs technologiques, immeubles de bureaux, entreprises et centres commerciaux : accès, électricité et eau relevés et pilotés depuis une console unique, clients WeChat et mobile pour recharges et signalement de pannes, et une plateforme cloud ouverte à l’intégration multi-acteurs.',
          points: [
            ['La visibilité d’abord', 'Une mesure fine des départs, des charges et du temps.'],
            ['Le stockage là où il paie', 'Du stockage appliqué à l’écrêtage, au secours et à l’autoconsommation.'],
            ['Une seule boucle de gestion', 'Données, stockage et contrôle en un système.'],
          ],
          steps: ['Auditer les flux d’énergie', 'Modéliser le cas de valeur', 'Déployer mesure et stockage', 'Gérer et optimiser'],
        },
        {
          slug: 'apartment-energy',
          name: 'Gestion énergétique des résidences',
          tagline: 'Le locatif, piloté depuis une seule plateforme.',
          description: 'Un système matériel et logiciel intelligent pour résidences centralisées, diffuses et en colocation — contrats, loyers et fluides gérés au même endroit.',
          longText: 'La solution résidences offre aux exploitants une console unique pour toute l’activité locative : contrats, loyers et services de gestion, aux côtés des équipements intelligents — serrures connectées, électricité, eau et gaz — avec relevé automatisé, statistiques, commande à distance et annonces aux résidents. Les locataires utilisent l’application ou le client WeChat pour consulter et recharger loyers et fluides, ouvrir leur porte à distance et signaler une panne. La plateforme cloud reste ouverte à l’intégration multi-acteurs de l’écosystème.',
          points: [
            ['Une console exploitant', 'Contrats, loyers, services et données des équipements — relevés, comptés et pilotés au même endroit.'],
            ['Une application qui répond', 'Soldes de loyer et de fluides, recharges, serrures à distance et signalement de panne en un geste.'],
            ['Une plateforme cloud ouverte', 'Intégration multi-acteurs pour l’écosystème résidentiel — exploitants, propriétaires et partenaires.'],
          ],
          steps: ['Cartographier le parc locatif', 'Installer serrures, compteurs et capteurs', 'Connecter console et applications', 'Exploiter, facturer et développer'],
        },
        {
          slug: 'campus-energy',
          name: 'Gestion énergétique des campus',
          tagline: 'L’eau et l’électricité du campus, sous contrôle.',
          description: 'Une solution intégrée de gestion de l’eau et de l’électricité pour les écoles et campus — matériel intelligent, communications IoT, plateforme cloud et applications mobiles en un seul système.',
          longText: 'Bâtie sur les compteurs d’électricité, compteurs d’eau et concentrateurs de Xili, la solution campus offre aux gestionnaires une plateforme unique pour les deux fluides : télérelevé et commande à distance des vannes et interrupteurs, prépaiement avec relances automatiques, et politiques de sécurité — plages d’alimentation programmées, protection contre les surcharges — pour internats et bâtiments d’enseignement.',
          points: [
            ['Relevé et commande à distance', 'Électricité et eau relevées à distance sur une seule plateforme, avec commande par chambre ou bâtiment.'],
            ['Prépaiement et facturation automatisée', 'Comptes prépayés, relances automatiques de solde et règlement clair pour chaque dortoir.'],
            ['La sécurité par la règle', 'Plages horaires programmées, protection contre surcharges et charges interdites, pensées pour le logement étudiant.'],
          ],
          steps: ['Cartographier eau et électricité du campus', 'Déployer compteurs et concentrateurs', 'Connecter plateforme cloud et applications', 'Exploiter, facturer et optimiser'],
        },
      ],
    },
    technology: {
      title: 'Technologie',
      heroTitle: 'La précision est un système d’exploitation.',
      heroBody: 'L’usine numérique de Xili relie cycle de vie produit, exécution de fabrication, équipements et collecte de données, du développement à la livraison.',
      sectionTitle: 'L’usine numérique',
      sectionBody: 'Depuis 2005, Xili construit sa fabrication autour de systèmes connectés — pour que la qualité soit mesurée, jamais supposée.',
      list: [
        ['Ingénierie de compteurs', 'Conception et vérification métrologiques, du circuit à l’étalonnage.'],
        ['BMS et communications', 'Gestion batterie et protocoles connectés des données d’énergie.'],
        ['Systèmes d’usine numérique', 'PLM, MES et données machines réunis en une boucle.'],
        ['Essais intégrés', 'Inspection automatisée, de la ligne au laboratoire.'],
      ],
      note: 'Conçu pour un déploiement fiable dans les infrastructures énergétiques modernes.',
      twinIndex: 'Jumeau numérique',
      twinTitle: 'L’usine, reflétée en données.',
      twinBody: 'Lignes, entrepôt et bancs d’essai alimentent un modèle numérique vivant de l’usine — la télémétrie qui pilote l’ordonnancement MES rend l’atelier sous forme de jumeau, où chaque machine s’observe, se simule et s’améliore.',
      twinTags: ['Lignes SMT et assemblage', 'Vérification automatisée', 'Entrepôt automatisé', 'Logistique AGV'],
      aiIndex: 'IA et intelligence',
      aiTitle: 'L’IA travaille sur la ligne, à nos côtés.',
      aiBody: 'L’intégration IA-fabrication de Xili a été retenue comme cas modèle provincial et national. L’intelligence n’est pas un projet pilote : elle est intégrée à l’inspection, à l’ordonnancement et à l’exploitation quotidienne.',
      aiList: [
        ['Applications de grands modèles', 'Des grands modèles d’IA intégrés à l’analyse qualité, au savoir industriel et aux flux d’exploitation — des réponses tirées des données de l’usine elle-même.'],
        ['Inspection par vision industrielle', 'Des systèmes de vision inspectent cartes et assemblages en ligne, au rythme de la production.'],
        ['Ordonnancement assisté par IA', 'Des algorithmes planifient sur 34 lignes et 270+ machines, en équilibrant délais d’appels d’offres et capacité dans le MES.'],
        ['Plateforme d’exploitation numérique', 'L’exploitation de toute l’entreprise rendue visuelle et pilotée par les données — en service depuis 2024.'],
      ],
      labsIndex: 'Laboratoires',
      labsTitle: 'Des laboratoires automatisés, jour et nuit.',
      labsBody: 'La vérification n’attend pas la relève. Le centre d’essais de Xili — accrédité CNAS, le service national chinois d’accréditation pour l’évaluation de la conformité — fait tourner ses bancs automatisés en continu : étalonnage, endurance, certification. Cette discipline explique vingt années consécutives de contrôles qualité nationaux et provinciaux réussis.',
      labsList: [
        ['Vérification et étalonnage automatisés', 'Des bancs robotisés vérifient les compteurs contre des étalons de référence — haut volume, prêt pour l’audit.'],
        ['Fiabilité et essais d’environnement', 'Chambres de température, d’humidité, de surtension et d’endurance : des années de contraintes terrain, condensées.'],
        ['CEM et sécurité électrique', 'Des bancs de compatibilité électromagnétique et de sécurité qualifient les produits pour le réseau et l’export.'],
        ['Essais batteries et énergies nouvelles', 'Des bancs cellule et pack cyclent, chargent et éprouvent les batteries LFP sur toute la plage de température.'],
      ],
      ipIndex: 'Normes et PI',
      ipTitle: 'Écrit dans les normes.',
      ipStats: [
        [132, '', 'Brevets délivrés'],
        [27, '', 'Brevets d’invention'],
        [148, '', 'Droits d’auteur logiciels'],
        [42, '', 'Normes nationales, sectorielles et de groupe corédigées'],
      ],
      ipNote: 'Distinctions : Prix chinois de l’excellence en brevets (2018), Prix chinois de l’invention et de l’entrepreneuriat, 2e classe (2025), et concentrateur DJTD23-XL31102 sélectionné « Made in Zhejiang » premium 2025.',
      milestonesTitle: 'Jalons d’ingénierie',
      milestones: [
        ['2005', 'Cap sur l’usine numérique', 'Les systèmes MES et PLM entrent en service.'],
        ['2023', 'Parc de Deqing en production', 'Ateliers numériques et entrepôt automatisé sur un parc intelligent de 120 000 m².'],
        ['2025', 'Fabrication dopée à l’IA', 'Intégration profonde IA-fabrication, cas modèle provincial et national.'],
      ],
    },
    about: {
      title: 'À propos',
      heroTitle: 'D’une station de pompage de quatre personnes au STAR Market.',
      heroBody: 'En 1968, Xili naît comme station de pompage de trois à quatre personnes de l’usine de machines agricoles du Lac de l’Ouest. En 2021, elle devient la première société du secteur des compteurs intelligents cotée au STAR Market.',
      storyTitle: 'Cinquante-sept ans, une conviction',
      storyBody: '« La qualité comme fondement, la technologie comme victoire » guide Xili depuis près de soixante ans — du compteur mécanique au compteur intelligent, de la fabrication traditionnelle à la production dopée à l’IA. Privatisée en 1999, au-delà des cent millions de yuans de revenus en 2010, cotée au STAR Market en 2021, et aujourd’hui dotée d’un parc industriel intelligent de 120 000 m² à Deqing. Xili exploite aujourd’hui 34 lignes de production et plus de 270 équipements de production et d’essai, sert plus de 500 clients dans 33 provinces chinoises et exporte notamment vers la Thaïlande, le Bangladesh, la Corée, les Philippines, le Ghana, le Chili, l’Équateur et le Pakistan — avec des produits conformes aux contrôles qualité nationaux et provinciaux depuis vingt années consécutives.',
      globalIndex: 'Empreinte mondiale',
      globalTitle: 'Mesuré chez nous. Reconnu ailleurs.',
      globalBody: 'Xili sert plus de 500 clients dans les 33 régions provinciales de Chine et exporte ses produits de comptage vers l’Asie du Sud-Est, l’Afrique, l’Europe de l’Est et l’Amérique du Sud. L’entreprise est membre de la DLMS User Association (Suisse) et de la STS Association (Afrique du Sud) — les deux organismes qui régissent la communication et le prépaiement des compteurs dans le monde.',
      globalHub: 'Hangzhou',
      globalMarkets: ['Thaïlande', 'Bangladesh', 'Corée du Sud', 'Philippines', 'Europe de l’Est', 'Ghana', 'Chili', 'Équateur', 'Pakistan'],
      globalStats: [
        [33, '', 'Régions provinciales en Chine'],
        [10, '', 'Marchés export'],
        [24, '', 'Partenaires de long terme'],
      ],
      investorIndex: 'Relations investisseurs',
      investorTitle: 'Cotée. Auditée. Distributrice de dividendes.',
      investorStats: [
        ['566 M¥', 'Chiffre d’affaires · 2025'],
        ['104 M¥', 'Résultat net · 2025'],
        ['5,5 %', 'Du chiffre d’affaires en R&D'],
        ['50,9 %', 'Taux de distribution du dividende'],
      ],
      investorNote: 'Hangzhou Xili Intelligent Technology Co., Ltd. — 688616.SH, STAR Market, Bourse de Shanghai. Comptes audités par Pan-China CPAs, opinion sans réserve. Relations investisseurs : zqb@cnxili.com',
      valuesTitle: 'Culture d’entreprise',
      values: [
        ['Héritage et ténacité', 'Cinquante-sept ans, d’une station de pompage à une société technologique cotée — l’élan fondateur demeure.'],
        ['Qualité d’abord, technologie gagnante', 'Le respect de la qualité et l’obstination technologique portent chacun de nos bonds.'],
        ['Grandir et partager ensemble', 'Une gestion institutionnalisée et des parcours de carrière pour chaque bâtisseur de l’équipe.'],
      ],
      timelineTitle: 'Jalons',
      timeline: [
        ['1968', 'Fondation', 'Débuts comme station de pompage de 3–4 personnes de l’usine de machines agricoles du Lac de l’Ouest.'],
        ['1999', 'Privatisation', 'Réforme actionnariale ; l’entreprise devient Hangzhou Xili Electric Energy Meter Manufacturing.'],
        ['2010', '100 M¥ de revenus', 'Le chiffre d’affaires dépasse cent millions de yuans après de solides appels d’offres State Grid.'],
        ['2016', 'Société par actions', 'Renommée Hangzhou Xili Intelligent Technology Co., Ltd. ; gouvernance moderne en place.'],
        ['2021', 'Cotation au STAR Market', 'Cotée le 18 mars 2021 (688616) — première société de compteurs intelligents cotée au STAR Market.'],
        ['2023', 'Parc de Deqing', 'Le parc industriel intelligent de 120 000 m² entre en pleine production : ateliers numériques, entrepôt automatisé.'],
        ['2024', 'Résultats records', 'Bénéfice net record de 104 millions de yuans ; plateforme d’exploitation numérique en service.'],
        ['2025', 'L’IA dans l’usine', 'L’intégration IA-fabrication devient cas modèle provincial et national ; revenus nouvelles énergies en hausse de 281 %.'],
      ],
      honorsTitle: 'Distinctions et qualifications',
      honorStats: [
        [132, '', 'Brevets délivrés'],
        [148, '', 'Droits d’auteur logiciels'],
        [42, '', 'Normes corédigées'],
        [40, '+', 'Résultats scientifiques certifiés'],
      ],
      honors: [
        'Fournisseur State Grid : classe A à chaque évaluation depuis 2019',
        'Centre d’essais accrédité CNAS',
        'Membre de la DLMS User Association et de la STS Association',
        'Usine verte et bas carbone nationale',
        'Entreprise nationale de démonstration en propriété intellectuelle',
        'PME nationale « spécialisée et innovante » (Zhejiang Xili)',
        'Institut de recherche d’entreprise clé provincial (2025)',
        'Prix chinois de l’excellence en brevets (2018)',
        'Première société de compteurs intelligents cotée au STAR Market',
      ],
      csrTitle: 'Responsabilité',
      csr: [
        ['Fabrication verte et bas carbone', 'Modernisation verte des procédés depuis 2014, primée au niveau provincial ; vérification carbone et certification d’empreinte en soutien des objectifs bas-carbone.'],
        ['Gouvernance responsable', 'Systèmes de management qualité, environnement, santé-sécurité et sécurité de l’information — avec un rapport ESG annuel.'],
        ['Solidarité et attention', 'Un fonds caritatif dédié a soutenu 55 patients avec 225 400 ¥ d’aides à fin 2025, aux côtés de dons anti-pandémie et de collectes de sang du personnel.'],
      ],
      officialAction: 'Site officiel Xili Technology',
      officialUrl: 'https://www.cnxili.com/en/WestForceProfile/index.aspx',
    },
    news: {
      title: 'Actualités',
      heroTitle: 'Actualités et jalons.',
      heroBody: 'Les annonces de l’entreprise et les jalons qui ont façonné Xili — mis à jour au fil de l’histoire.',
      items: [
        ['2026', 'Contrats', 'Plus de 162 millions de yuans remportés auprès de State Grid', 'Xili est retenue au premier appel d’offres 2026 de State Grid en équipements de comptage — compteurs monophasés classe A, triphasés classes B/C, terminaux de fusion intelligents et transformateurs de mesure — pour 162 millions de yuans au total, avec d’autres succès au Hubei, en Anhui, au Heilongjiang et à Shanghai.', 'meter-line'],
        ['2026', 'ESG', 'Publication des rapports ESG 2025', 'Hangzhou Xili et Zhejiang Xili publient leurs rapports environnementaux, sociaux et de gouvernance 2025, étendant la transparence aux activités comptage et énergies nouvelles.', 'pv-solution'],
        ['2026', 'Résultats', 'Exercice 2025 : profit stable et 52,9 M¥ de dividendes', 'Chiffre d’affaires de 566 millions de yuans, résultat net de 104 millions, flux de trésorerie d’exploitation en hausse de 53 %. Un dividende de 3 ¥ par 10 actions reverse 50,9 % du résultat net aux actionnaires.', 'zhuantang-hq'],
        ['2026', 'Fabrication', 'L’usine du futur retenue comme projet de démonstration du Zhejiang', 'La modernisation « usine du futur » des terminaux de comptage intelligents est retenue sur la liste 2026 des projets de démonstration de transformation productive de la province du Zhejiang.', 'robot-cell'],
        ['2026', 'Distinction', 'Usine verte et bas carbone de niveau national', 'Xili Technology reçoit la distinction nationale « usine verte et bas carbone », saluant une fabrication sobre en énergie et en émissions.', 'deqing-park'],
        ['2025', 'Jalon', 'L’intégration IA-fabrication devient cas modèle national', 'L’intégration profonde de l’IA dans la fabrication de Xili est retenue comme cas modèle provincial et national ; les revenus de Xili New Energy progressent de 281 % sur un an.', 'robot-glow'],
        ['2024', 'Résultats', 'Bénéfice net record de 104 millions de yuans', 'Le bénéfice net annuel atteint un record de 104 millions de yuans ; la plateforme d’exploitation numérique entre en service.', 'hall'],
        ['2024', 'Certification', 'Certification ONU ECE pour composants de véhicules', 'Zhejiang Xili New Energy obtient le certificat de conformité de production ONU ECE E57*COP*1169, délivré par l’Autorité d’homologation de la République de Saint-Marin — la production en série de composants pour véhicules est reconnue par les 56 États membres de l’Accord de 1958 de l’ONU.', 'doc-unece-cert'],
        ['2023', 'Fabrication', 'Le parc industriel de Deqing en pleine production', 'Le parc intelligent de 120 000 m² entre en pleine production : ateliers numériques et entrepôt automatisé en service.', 'campus-aerial'],
        ['2021', 'Jalon', 'Xili Technology entre au STAR Market', 'Hangzhou Xili Intelligent Technology (688616.SH) est cotée au STAR Market de la Bourse de Shanghai — un engagement public envers l’ingénierie de précision.', 'listing-2021'],
        ['2005', 'Fabrication', 'Le cap de l’usine numérique', 'Xili relie cycle de vie produit, exécution de fabrication et données machines en une seule boucle — une qualité mesurée, jamais supposée.', 'factory-2005'],
        ['1968', 'Héritage', 'Naissance de l’héritage du comptage', 'Le socle industriel du comptage électrique qui ancre encore la culture de précision de Xili.', 'heritage-1968'],
      ],
      note: 'Les annonces suivantes sont publiées après vérification officielle.',
    },
    careers: {
      title: 'Carrières',
      heroTitle: 'Construisez les instruments du réseau.',
      heroBody: 'Le travail de précision demande des gens précis. Rejoignez une équipe où la mesure est un art et l’énergie une mission.',
      whyTitle: 'Pourquoi Xili',
      why: [
        ['De vraies infrastructures', 'Votre travail part dans les réseaux, les usines et les foyers — sur des décennies.'],
        ['Une profondeur d’ingénierie', 'Métrologie, BMS, communications et systèmes industriels sous un même toit.'],
        ['Une plateforme cotée', 'La stabilité d’une société cotée au STAR Market, la concentration d’un spécialiste.'],
      ],
      areasTitle: 'Directions de recrutement',
      areas: [
        ['Ingénierie R&D', 'Comptage, BMS, embarqué et communications.'],
        ['Fabrication & supply chain', 'Usine numérique, procédés et équipements.'],
        ['Qualité & essais', 'Vérification métrologique, de la ligne au laboratoire.'],
        ['Marchés & ventes', 'Programmes réseau et développement international.'],
      ],
      action: 'Présentez-vous',
      note: 'Envoyez votre CV et la direction qui vous intéresse — nous répondons à toute candidature sérieuse.',
    },
    contact: {
      title: 'Contact',
      heroTitle: 'Rendons l’énergie plus lisible.',
      heroBody: 'Indiquez-nous où votre système énergétique a besoin de plus de précision, de visibilité ou de résilience.',
      action: 'Démarrer une conversation',
      channelsTitle: 'Nous joindre',
      email: 'xenergy@cnxili.com',
      offices: 'Hangzhou · Deqing · Chine',
      officeTitle: 'Implantations',
      locations: [
        ['zhuantang-hq', 'Hangzhou · Zhuantang', 'Siège de Xili Technology'],
        ['deqing-park', 'Huzhou · Deqing', 'Parc industriel intelligent de Deqing'],
      ],
      emailTitle: 'E-mail',
      responseNote: 'Nous répondons aux demandes de solution sous deux jours ouvrés.',
    },
    footer: {
      descriptor: 'Intelligence énergétique',
      colProducts: 'Produits',
      colSolutions: 'Solutions',
      colCompany: 'Entreprise',
      legal: '© 2026 Xili Technology. Tous droits réservés.',
    },
  },

  zh: {
    locale: '中',
    code: 'zh',
    meta: {
      title: '西力科技 — 智慧能源',
      description: '以精准为基础的智慧能源体系，从电力计量到可靠储能。',
    },
    common: {
      home: '首页',
      explore: '了解详情',
      learnMore: '了解更多',
      viewAll: '查看全部',
      backTo: '返回',
      discuss: '洽谈解决方案',
      contactUs: '联系我们',
      menu: '菜单',
      close: '关闭菜单',
      related: '相关推荐',
      keyPoints: '核心能力',
      process: '交付流程',
      categories: '产品线',
      directions: '方案方向',
      scroll: '向下浏览',
      breadcrumbProducts: '产品体系',
      breadcrumbSolutions: '解决方案',
      imageSoon: '图片即将上线',
      readMore: '阅读更多',
    },
    nav: {
      products: '产品体系',
      solutions: '解决方案',
      technology: '技术实力',
      about: '关于西力',
      news: '新闻动态',
      careers: '加入我们',
      contact: '联系我们',
    },
    marquee: ['智能计量', '用电采集', '电池智能', '储能系统', '数字化工厂', '精准工程'],
    home: {
      heroKicker: '质量为本 · 科技制胜',
      heroTitle: '智能电表 · 电池系统 · 储能系统。',
      heroBody: '杭州西力打造电力级的电能计量与储能系统——从电网边缘的智能计量到工商业储能。2021 年登陆科创板。',
      heroPrimary: '了解产品体系',
      heroSecondary: '认识西力',
      stats: [
        [1968, '', '创业起点'],
        [2021, '', '科创板上市'],
        [500, '+', '服务客户'],
        [33, '', '覆盖省级区域'],
      ],
      pillarsIndex: '总览',
      pillarsTitle: '一层智能底座，四大核心能力。',
      pillarsBody: '西力将电能计量、用电信息采集、电池智能与储能系统整合为一个专注的能源产品体系。',
      pillars: [
        ['01', '智能计量', '覆盖电网边缘每个节点的精准电能计量。'],
        ['02', '用电采集', '贯通用电数据与能源流的互联可视化。'],
        ['03', '电池智能', '以可靠性为核心的电池管理技术。'],
        ['04', '储能系统', '从便携电源到工商业规模的分布式系统。'],
      ],
      productsIndex: '产品体系',
      productsTitle: '围绕能源链构建的产品体系。',
      productsBody: '计量、电池、储能三大产品线，每一条都有独立的详细介绍。',
      solutionsIndex: '解决方案',
      solutionsTitle: '让能源加速向前的系统。',
      solutionsBody: '五个解决方案方向——电网、综合能源、工商业、公寓与校园，由同一套精准的能源语言贯通。',
      technologyIndex: '技术实力',
      technologyTitle: '精准，是一套运行系统。',
      technologyBody: '数字化工厂贯通产品生命周期、制造执行与数据采集，覆盖从研发到交付的全流程。',
      technologyAction: '走进数字化工厂',
      newsIndex: '新闻动态',
      newsTitle: '来自西力的最新动态。',
      partnersIndex: '合作伙伴',
      partnersTitle: '与能源链上的同行者并肩。',
      partnersBody: '与西力携手同行的电网、电池与新能源领军企业。',
      zhFirst: true,
      ctaTitle: '让能源更加清晰可读。',
      ctaBody: '告诉我们您的能源系统在哪些方面需要更高的精准度、可视化与可靠性。',
    },
    products: {
      title: '产品体系',
      catalogIndex: '产品目录',
      heroTitle: '围绕能源链构建的产品体系。',
      heroBody: '从计量级测量到电池与储能——每一条产品线都建立在同一种纪律之上：可审计的精准。',
      categories: [
        {
          slug: 'power-intelligence',
          name: '电力智能',
          tagline: '让电网信赖的计量。',
          description: '面向电能计量与用电数据可视化的精密仪器，是一切能源决策的基础。',
          longText: '从户用计量点到电力公司的采集网络，西力电力智能产品线将电与水转化为结构化、可审计的数据。数十年计量积淀，与现代通信、智能配网硬件和持续生长的物联生态相结合。',
          items: [
            ['智能电能表', '面向现代电网精度等级要求的单相与三相电能计量产品。'],
            ['智能水表', '基于 NB-IoT 与 LoRa 的远传、阀控与超声波水计量产品。'],
            ['采集与配网', '采集终端、集中器、智能断路器与物联网计量箱，覆盖供电节点。'],
          ],
          points: ['计量级精度', '国网供应商绩效评价：2019 年以来历次 A 类', '规模化部署经验', '互联通信能力'],
        },
        {
          slug: 'battery-systems',
          name: '电池系统',
          tagline: '磷酸铁锂电芯，为可靠而生。',
          description: '浙江西力新能源动力电池——磷酸铁锂体系、钢壳全极耳电芯、BMS 智慧管理系统全域监控。',
          longText: '浙江西力新能源 2023 年在湖州莫干山国家高新区成立，电芯研发聚焦四大体系：安全性（宽温域 LFP）、快充（1–3C，最高 5C）、高能量密度（170Wh/kg）与长循环寿命（2000–2500 周）。生产配备 70 余台全自动注塑机、6 条 SMT 全自动贴片产线与多条自动 PACK 产线，MES 系统实现产品全寿命品质追踪。',
          items: [
            ['动力电池', '磷酸铁锂钢壳全极耳电芯——内阻低、散热好，不鼓壳、不裂壳，可靠性强。'],
            ['电芯技术', '四大研发体系：安全性、1–3C 快充、170Wh/kg 高能量密度、2000–2500 周长循环。'],
            ['BMS 智慧管理', '全域监控；兼容一线通/485/CAN/UART 协议；匹配 IoT/NB-IoT（蓝牙/WIFI/GPS/北斗）。'],
          ],
          points: ['磷酸铁锂体系 · 宽温域', '170Wh/kg 高能量密度', '2000–2500 周循环寿命'],
        },
        {
          slug: 'energy-storage',
          name: '储能系统',
          tagline: '每一种规模的可靠性。',
          description: '覆盖便携、户用与工商业应用的储能系统。',
          longText: '从便携式储能电源到户用与工商业装机，储能产品线将西力在计量与电池方面的专长延伸为完整的能源系统——存储、调度并保障电力。',
          items: [
            ['便携式储能电源', '移动 LFP 能源——如 1152Wh/48V 仅 9kg，循环 1500 次容量仍大于 70%。'],
            ['户用储能', '与屋顶光伏配套的家庭系统，支持自发自用与备电。'],
            ['工商业储能', '面向工业与商业能源管理的可扩展系统。'],
          ],
          points: ['IP67 级防水 · V0 级阻燃', 'BMS 智慧管理全域监控', '数字化管理平台（PC/小程序）'],
        },
      ],
    },
    solutions: {
      title: '解决方案',
      heroTitle: '让能源加速向前的系统。',
      heroBody: '五个解决方案方向——电网、综合能源、工商业、公寓与校园，由同一套精准的能源语言贯通。',
      items: [
        {
          slug: 'grid-intelligence',
          name: '电网智能',
          tagline: '更清晰可见的电网边缘。',
          description: '面向电力公司与电网运营方的智能计量、用电采集与电能计量系统。',
          longText: '电网智能始于计量点。西力将智能电表、采集终端与计量箱系统组合为成套部署方案，让运营方对电网边缘拥有精准、连续的可视化。',
          points: [
            ['精准计量', '按电力项目精度等级要求打造的计量产品。'],
            ['互联采集', '将用电数据可靠传入电力系统的终端与集中器。'],
            ['部署经验', '以数十年计的计量积淀，应用于现代化改造项目。'],
          ],
          steps: ['评估计量现状', '配置产品与通信', '规模化部署与校验', '存量设备持续服务'],
        },
        {
          slug: 'pv-storage-charging',
          name: '光伏 · 储能 · 充电',
          tagline: '一体化的能源闭环。',
          description: '面向光伏发电、储能与充电的一体化解决方案方向。',
          longText: '发电、储能与充电是一个系统，而非三个。该方向将光伏输入、电池储能与充电负载纳入统一的计量与控制之下——让能源在最需要、最有价值的时刻流向该去的地方。',
          points: [
            ['面向发电的储能', '按真实光伏出力曲线配置与控制储能。'],
            ['充电一体化', '充电负载作为能源闭环的一部分统一管理。'],
            ['全程可计量', '西力的计量纪律贯穿系统中每一路能量流。'],
          ],
          steps: ['分析发电与负载曲线', '设计一体化系统', '安装与调试', '全程可视化运行'],
        },
        {
          slug: 'commercial-energy',
          name: '工商业能源管理',
          tagline: '让能源成为经营优势。',
          description: '面向工业与商业需求的综合能源管理解决方案方向。',
          longText: '对工商业场所而言，能源是可管理的成本，也是韧性问题。该方向将计量、储能与管理相结合，让运营者清晰看见能耗，并有信心地采取行动。方案已应用于科技园区、商业楼宇、企业单位与综合体商场：门禁、电、水数据在同一管理端抄收、统计与控制，微信与 APP 客户端支持查询、充值与故障报修，云服务平台支持多方互联。',
          points: [
            ['可视化优先', '覆盖回路、负载与时段的精细计量。'],
            ['储能用在刀刃上', '将工商业储能应用于削峰、备电与自发自用。'],
            ['一个管理闭环', '数据、储能与控制协同为一个系统。'],
          ],
          steps: ['能源流审计', '价值模型测算', '部署计量与储能', '持续管理与优化'],
        },
        {
          slug: 'apartment-energy',
          name: '公寓能源管理',
          tagline: '租住运营，一个平台跑通。',
          description: '面向集中式、分散式与共享公寓的智能软硬件管理系统——合同、租金与水电气在同一平台管理。',
          longText: '智慧公寓方案为运营商提供覆盖租住业务全流程的管理端：合同、租金与代理物业服务，连同门锁、电、水、气等智能设备的数据抄收统计、远程控制与信息发布。租户通过 APP 或微信客户端查询并充值房租与水电气费、远程开锁、控制智能硬件、一键报修。云服务平台支持多方互联，服务智慧公寓生态伙伴。',
          points: [
            ['一个运营管理端', '合同、租金、物业服务与智能设备数据——同一平台抄收、统计与控制。'],
            ['有回应的租户端', '房租水电气查询与充值、远程门锁、智能硬件控制、一键故障报修。'],
            ['开放的云平台', '面向公寓生态的多方互联——运营商、业主与服务伙伴互利共赢。'],
          ],
          steps: ['梳理租住房源现状', '部署智能门锁、表计与传感', '接入管理端与租户端', '运营结算，持续增长'],
        },
        {
          slug: 'campus-energy',
          name: '校园能源管理',
          tagline: '让校园水电清晰可控。',
          description: '面向学校与校园的水电一体化智能管理方案——智能硬件、物联网通信、云平台与移动端合为一个系统。',
          longText: '方案基于西力自研的智能电表、智能水表与集中器，为校园管理者提供水电合一的管理平台：远程抄表与远程阀控/跳合闸，预付费与自动催缴，并可针对宿舍与教学楼设置定时供电、恶性负载识别与过载保护等安全策略。',
          points: [
            ['远程抄表与控制', '水电数据同平台远程采集，支持按房间、按楼栋远程控制开关与阀门。'],
            ['预付费与自动催缴', '预付费账户、余额不足自动提醒，每间宿舍费用清晰可结。'],
            ['以策略保安全', '定时供电时段、过载与恶性负载保护，为学生住宿场景专门设计。'],
          ],
          steps: ['调研校园水电现状', '部署智能表计与集中器', '接入云平台与移动端', '运营、计费与持续优化'],
        },
      ],
    },
    technology: {
      title: '技术实力',
      heroTitle: '精准，是一套运行系统。',
      heroBody: '西力数字化工厂贯通产品生命周期、制造执行、设备与数据采集系统，覆盖从研发到交付的全流程。',
      sectionTitle: '数字化工厂',
      sectionBody: '自 2005 年起，西力围绕互联系统构建制造体系——质量靠测量验证，而非假设。',
      list: [
        ['智能电表工程', '从电路到校准的计量级设计与验证。'],
        ['BMS 与通信', '电池管理与承载能源数据的互联协议。'],
        ['数字化工厂系统', 'PLM、MES 与设备数据汇成一个制造闭环。'],
        ['一体化检测', '从产线到实验室的自动化检验。'],
      ],
      note: '为现代能源基础设施的可靠部署而构建。',
      twinIndex: '数字孪生',
      twinTitle: '一座在数据中运行的工厂。',
      twinBody: '产线、立库与检测台架汇入同一个实时数字模型——驱动 MES 排产的遥测数据，同时把车间渲染为一座“活的孪生工厂”：每台设备都可观测、可仿真、可优化。',
      twinTags: ['SMT 与组装产线', '自动化检定', '智能立体仓库', 'AGV 物流'],
      aiIndex: 'AI 与智能化',
      aiTitle: 'AI 与我们并肩上产线。',
      aiBody: '西力 AI 与制造深度融合入选省级、国家级典型案例。在这里，智能化不是试点项目——它嵌入在检测、排产与日常运营之中。',
      aiList: [
        ['大模型应用', 'AI 大模型嵌入质量分析、生产知识与运营流程——答案来自工厂自己的数据。'],
        ['机器视觉检测', '视觉系统在线检测电路板与组件，以产线速度拦截缺陷，不让问题流向下游。'],
        ['AI 辅助排产', '算法在 34 条产线、270 余台设备间统筹规划，在 MES 中平衡交付节点与产能。'],
        ['数字化运营平台', '公司级运营的可视化、数据化管理——2024 年上线，贯通订单到交付。'],
      ],
      labsIndex: '实验室',
      labsTitle: '全天候运转的自动化实验室。',
      labsBody: '检定不等换班。西力测试中心已通过中国合格评定国家认可委员会（CNAS）认可，自动化台架持续完成校准、老化与认证——这是连续二十年通过国家级与省级质量监督抽查背后的硬功夫。',
      labsList: [
        ['自动化检定与校准', '机械化台架对照基准标准批量检定电表——高通量、少人工、可审计。'],
        ['可靠性与环境试验', '高低温、湿热、浪涌与寿命试验箱，把多年现场应力浓缩进实验室。'],
        ['EMC 与电气安全', '电磁兼容与安全测试台架，为电网环境与出口市场做产品资质验证。'],
        ['电池与新能源测试', '电芯与 PACK 台架在全温度窗口内对磷酸铁锂电池充放循环与滥用测试。'],
      ],
      ipIndex: '标准与知识产权',
      ipTitle: '把名字写进标准里。',
      ipStats: [
        [132, '', '授权专利'],
        [27, '', '发明专利'],
        [148, '', '软件著作权'],
        [42, '', '参与制定国家、行业及团体标准'],
      ],
      ipNote: '荣誉包括：中国专利优秀奖（2018）、中国发明协会发明创业奖·成果奖二等奖（2025），DJTD23-XL31102 型集中器入选 2025 年“浙江制造精品”。',
      milestonesTitle: '工程里程碑',
      milestones: [
        ['2005', '数字化工厂之路', '制造执行与产品生命周期系统上线。'],
        ['2023', '德清产业园投产', '12 万平方米智能化产业园：数字化车间、智能立库投用。'],
        ['2025', 'AI 赋能制造', 'AI 与制造深度融合，入选省级、国家级典型案例。'],
      ],
    },
    about: {
      title: '关于西力',
      heroTitle: '从三四人的排灌站，到科创板上市。',
      heroBody: '1968 年，西力从西湖农机厂三四人的排灌站起步；2021 年，成为智能电表行业首家科创板上市企业。五十七载，初心不改。',
      storyTitle: '五十七载，一个信念',
      storyBody: '“质量为本，科技制胜”——这是贯穿西力近六十年发展的核心经营理念。从机械表到智能表，从传统制造到 AI 赋能，每一次技术跨越，都源于对质量的敬畏与对科技的执着。1999 年改制民营，2010 年营收首破亿元，2021 年登陆科创板，如今在德清运营 12 万平方米的智能化产业园。今天的西力拥有 34 条生产线、270 余台（套）生产与试验设备，服务客户 500 余家、覆盖全国 33 个省级区域，产品远销泰国、孟加拉、韩国、菲律宾、加纳、智利、厄瓜多尔、巴基斯坦等市场——并连续二十年通过国家级与省级质量监督抽查。',
      globalIndex: '全球布局',
      globalTitle: '深耕国内，走向海外。',
      globalBody: '西力服务客户 500 余家，覆盖全国 33 个省级区域；计量产品远销东南亚、非洲、东欧与南美市场。公司是瑞士 DLMS 技术协会与南非 STS 技术协会会员——这两个国际组织定义着全球电表的通信与预付费标准。',
      globalHub: '杭州',
      globalMarkets: ['泰国', '孟加拉', '韩国', '菲律宾', '东欧', '加纳', '智利', '厄瓜多尔', '巴基斯坦'],
      globalStats: [
        [33, '', '覆盖省级区域'],
        [10, '', '海外出口市场'],
        [24, '', '长期合作伙伴'],
      ],
      investorIndex: '投资者关系',
      investorTitle: '上市公司的透明度。',
      investorStats: [
        ['5.66 亿元', '2025 年营业收入'],
        ['1.04 亿元', '2025 年归母净利润'],
        ['5.5%', '研发投入占营收比'],
        ['50.9%', '现金分红占净利润比'],
      ],
      investorNote: '杭州西力智能科技股份有限公司——688616.SH，上海证券交易所科创板。天健会计师事务所出具标准无保留意见审计报告。投资者关系：zqb@cnxili.com',
      valuesTitle: '企业文化',
      values: [
        ['历史传承 · 奋斗基因', '五十七载，从排灌站到上市科技企业，创业的拼劲始终未变。'],
        ['质量为本 · 科技制胜', '对质量的敬畏与对科技的执着，驱动每一次技术跨越。'],
        ['人才团队 · 共创共享', '制度化、流程化的精细管理，让每一位奋斗者在这里收获成长、实现价值。'],
      ],
      timelineTitle: '发展里程碑',
      timeline: [
        ['1968', '创业起点', '从西湖农机厂三四人的排灌站起步。'],
        ['1999', '改制民营', '完成股份制改造，更名"杭州西力电能表制造有限公司"，从集体所有制转型民营。'],
        ['2010', '营收破亿', '国网集中招标中崭露头角，销售收入首次突破亿元大关。'],
        ['2016', '股份制改造', '更名"杭州西力智能科技股份有限公司"，建立现代企业治理结构。'],
        ['2021', '科创板上市', '3 月 18 日正式上市（股票代码 688616），成为智能电表行业首家科创板上市企业。'],
        ['2023', '德清产业园投产', '12 万平方米智能化产业园全面投产，数字化车间、智能立库投用。'],
        ['2024', '业绩创新高', '全年净利润达 1.04 亿元创历史新高；数字化运营平台上线。'],
        ['2025', 'AI 深度融合', 'AI 与制造深度融合入选省级、国家级典型案例；新能源销售收入同比增长 281%。'],
      ],
      honorsTitle: '荣誉资质',
      honorStats: [
        [132, '', '授权专利'],
        [148, '', '软件著作权'],
        [42, '', '参与制定标准'],
        [40, '+', '科技成果鉴定证书'],
      ],
      honors: [
        '国网供应商绩效评价：2019 年以来历次最高等级 A 类',
        'CNAS 认可测试中心',
        '瑞士 DLMS 技术协会会员 · 南非 STS 技术协会会员',
        '国家级绿色低碳工厂',
        '国家知识产权示范企业',
        '国家级专精特新中小企业（浙江西力）',
        '省级重点企业研究院（2025）',
        '中国专利优秀奖（2018）',
        '智能电表行业首家科创板上市企业',
      ],
      csrTitle: '社会责任',
      csr: [
        ['绿色发展 · 低碳制造', '自 2014 年起持续推动绿色工艺改造与节能降耗，多项成果获省级环境创新奖项；持续开展碳核查与碳足迹认证，助力"双碳"目标。'],
        ['责任治理 · ESG', '建立并完善质量、环境、职业健康安全、信息安全管理体系，每年发布 ESG 报告，系统披露环境、社会及治理实践与绩效。'],
        ['公益与员工关怀', '设立专项慈善基金，截至 2025 年底累计资助 55 位患者、发放善款 22.54 万元；组织公益捐赠与员工无偿献血。'],
      ],
      officialAction: '西力科技官方网站',
      officialUrl: 'https://www.cnxili.com/en/WestForceProfile/index.aspx',
    },
    news: {
      title: '新闻动态',
      heroTitle: '新闻与里程碑。',
      heroBody: '公司公告与塑造西力的重要节点——故事仍在继续，此页持续更新。',
      items: [
        ['2026', '中标喜讯', '国家电网中标金额超 1.62 亿元', '西力中标国家电网 2026 年营销项目第一次计量设备招标——A 级单相、B/C 级三相智能电能表、智能融合终端与计量用互感器，中标总额约 1.62 亿元；并相继中标国网湖北、安徽、黑龙江与上海项目。', 'meter-line'],
        ['2026', 'ESG', '发布 2025 年度 ESG 报告', '杭州西力与浙江西力分别发布 2025 年度环境、社会及治理报告，信息披露覆盖计量与新能源两大业务板块。', 'pv-solution'],
        ['2026', '经营业绩', '2025 年度业绩稳健，分红 5288 万元', '2025 年营业收入 5.66 亿元，归母净利润 1.04 亿元，经营性现金流增长 53%。每 10 股派现 3 元，分红占净利润 50.9%。', 'zhuantang-hq'],
        ['2026', '智能制造', '“未来工厂”技改入选浙江省示范项目', '智能能源计量终端未来工厂技改项目入选浙江省 2026 年度生产制造方式转型示范项目计划。', 'robot-cell'],
        ['2026', '荣誉', '获评国家级绿色低碳工厂', '西力科技获评"国家级绿色低碳工厂"，节能低碳的智能制造体系再获国家级认可。', 'deqing-park'],
        ['2025', '里程碑', 'AI 与制造深度融合入选国家级典型案例', '西力 AI 与制造深度融合入选省级、国家级典型案例；西力新能源销售收入同比增长 281%。', 'robot-glow'],
        ['2024', '经营业绩', '全年净利润 1.04 亿元创历史新高', '全年净利润达 1.04 亿元，创历史新高；数字化运营平台上线，实现可视化、数字化管理。', 'hall'],
        ['2024', '认证', '获联合国 ECE 车辆部件认证', '浙江西力新能源获得由圣马力诺共和国型式认证机构颁发的联合国 ECE 生产一致性证书（E57*COP*1169），车辆部件批量生产资质获联合国《1958 年协定书》56 个成员国认可。', 'doc-unece-cert'],
        ['2023', '智能制造', '德清智能化产业园全面投产', '12 万平方米产业园全面投产，数字化车间、智能立库投用。', 'campus-aerial'],
        ['2021', '里程碑', '西力科技登陆科创板', '杭州西力智能科技（688616.SH）在上海证券交易所科创板上市——对精准工程的公开承诺。', 'listing-2021'],
        ['2005', '智能制造', '数字化工厂之路启程', '西力将产品生命周期、制造执行与设备数据汇成一个闭环——质量靠测量验证，而非假设。', 'factory-2005'],
        ['1968', '行业积淀', '电能计量积淀开启', '深耕电能计量的行业根基，至今仍支撑着西力的精度文化。', 'heritage-1968'],
      ],
      note: '更多公告将在官方核实后发布。',
    },
    careers: {
      title: '加入我们',
      heroTitle: '打造电网信赖的仪器。',
      heroBody: '精准的工作需要精准的人。加入一支把计量当作工艺、把能源当作使命的团队。',
      whyTitle: '为什么选择西力',
      why: [
        ['真实的基础设施', '你的作品进入电网、工厂与家庭——以数十年计，而非以冲刺计。'],
        ['工程深度', '计量、BMS、通信与制造系统同在一个屋檐下。'],
        ['上市平台', '科创板上市公司的稳定，专精企业的专注。'],
      ],
      areasTitle: '招聘方向',
      areas: [
        ['研发工程', '计量、BMS、嵌入式与通信工程。'],
        ['制造与供应链', '数字化工厂运营、工艺与设备工程。'],
        ['质量与检测', '从产线到实验室的计量级验证。'],
        ['市场与销售', '电网项目与国际市场拓展。'],
      ],
      action: '自我介绍',
      note: '发送简历并注明感兴趣的方向——每一份认真的申请我们都会回复。',
    },
    contact: {
      title: '联系我们',
      heroTitle: '让能源更加清晰可读。',
      heroBody: '告诉我们您的能源系统在哪些方面需要更高的精准度、可视化与可靠性。',
      action: '开始交流',
      channelsTitle: '联系方式',
      email: 'xenergy@cnxili.com',
      offices: '杭州 · 德清 · 中国',
      officeTitle: '办公地点',
      locations: [
        ['zhuantang-hq', '杭州 · 转塘', '西力科技总部'],
        ['deqing-park', '湖州 · 德清', '德清智能化产业园'],
      ],
      emailTitle: '电子邮箱',
      responseNote: '方案类咨询将在两个工作日内回复。',
    },
    footer: {
      descriptor: '智慧能源',
      colProducts: '产品体系',
      colSolutions: '解决方案',
      colCompany: '公司',
      legal: '© 2026 西力科技 版权所有',
    },
  },
}
