export const locales = ['en', 'fr', 'zh']

/* Partner names are proper nouns shared across locales: [latin, chinese].
   Entries without a public latin name carry the Chinese mark only. */
/* [latin, zh, logo] — logos scraped from cnxili.com and xilixn.com partner walls. */
export const partnersList = [
  ['State Grid', '国家电网', 'state-grid'],
  ['China Southern Power Grid', '中国南方电网', 'southern-grid'],
  ['Tianneng Group', '天能控股集团', 'tianneng'],
  ['EVE Energy', '亿纬锂能', 'eve'],
  ['Ganfeng Lithium', '赣锋锂业', 'ganfeng'],
  ['Guoxuan High-Tech', '国轩高科', 'guoxuan'],
  ['AIMA', '爱玛', 'aima'],
  ['DFD New Energy', '多氟多新能源', 'dfd'],
  ['CB New Energy', '中比新能源', 'cb-new-energy'],
  ['TONLY', '台翔', 'tonly'],
  ['Today Sunshine', '今日阳光', 'today-sunshine'],
  ['SENUO', '赛诺', 'senuo'],
  ['Shansu', '闪速', 'shansu'],
  ['Chaoliyuan', '超力源', 'chaoliyuan'],
  ['GEYI Group', '格一集团', 'geyi'],
  ['ETSU', '艾越', 'etsu'],
  ['CPNN', '中国电力新闻网', 'cpnn'],
]


/* Real product catalogue for the power-intelligence line. Photos live in
   /assets/products; names keyed by locale code. */
export const content = {
  en: {
    locale: 'EN',
    code: 'en',
    meta: {
      title: 'Xili Technology — Energy intelligence',
      description: 'Smart energy intelligence, built on precision from measurement to resilient storage.',
    },
    common: {
      home: 'Home',
      explore: 'Explore',
      learnMore: 'Learn more',
      viewAll: 'View all',
      backTo: 'Back to',
      discuss: 'Discuss a solution',
      contactUs: 'Contact us',
      menu: 'Menu',
      close: 'Close menu',
      related: 'Related',
      keyPoints: 'Key capabilities',
      process: 'How we deliver',
      categories: 'Product lines',
      directions: 'Solution directions',
      scroll: 'Scroll',
      breadcrumbProducts: 'Products',
      breadcrumbSolutions: 'Solutions',
      imageSoon: 'Image coming soon',
      readMore: 'Read more',
    },
    nav: {
      products: 'Products',
      solutions: 'Solutions',
      technology: 'Technology',
      about: 'About us',
      news: 'News',
      careers: "We're hiring",
      contact: 'Contact',
    },
    marquee: ['Smart metering', 'Grid-edge data', 'Distribution network', 'Energy storage', 'Digital management', 'Precision engineering'],
    home: {
      heroKicker: 'Powering the future grid with precision',
      heroTitle: 'Smart meters. Distribution networks. Energy storage.',
      heroBody: 'Hangzhou Xili builds utility-grade electricity measurement, distribution-network equipment and energy-storage systems — from grid-edge smart metering to commercial storage. Listed on the STAR Market since 2021.',
      heroPrimary: 'Explore products',
      heroSecondary: 'Meet Xili',
      stats: [
        [1968, '', 'Founded'],
        [2021, '', 'STAR Market listing'],
        [500, '+', 'Clients served'],
        [33, '', 'Provinces & regions covered'],
      ],
      pillarsIndex: 'Overview',
      pillarsTitle: 'One intelligence layer. Three essential capabilities.',
      pillarsBody: 'Xili connects electricity measurement, distribution-network equipment and energy storage in one focused energy portfolio.',
      pillars: [
        ['01', 'Smart metering', 'Accurate electricity measurement at every point of the grid edge.'],
        ['02', 'Distribution network', 'Enclosures, low-voltage cabinets and pole-mounted switchgear around the measurement point.'],
        ['03', 'Energy storage', 'Distributed systems from portable power to commercial scale.'],
      ],
      productsIndex: 'Products',
      productsTitle: 'A portfolio built around the energy chain.',
      productsBody: 'Three product lines covering measurement, distribution and storage — each with its own dedicated overview.',
      solutionsIndex: 'Solutions',
      solutionsTitle: 'Systems that move energy forward.',
      solutionsBody: 'Five solution directions — grid, integrated energy, commercial, apartment and campus — connected by one precise energy language.',
      technologyIndex: 'Technology',
      technologyTitle: 'Precision is an operating system.',
      technologyBody: 'An R&D team of over 100 and a provincial key research institute, feeding 34 automated lines under one digital management platform — from development to delivery.',
      technologyAction: 'Inside R&D and manufacturing',
      newsIndex: 'News',
      newsTitle: 'Latest from Xili.',
      partnersIndex: 'Cooperative partners',
      partnersTitle: 'Trusted across the energy chain.',
      partnersBody: 'Grid utilities, new-energy leaders and the upstream and downstream partners across Xili’s supply chain.',
      zhFirst: false,
      ctaTitle: 'Let’s make energy more legible.',
      ctaBody: 'Tell us where your energy system needs more precision, visibility or resilience.',
    },
    products: {
      title: 'Products',
      catalogIndex: 'Product catalogue',
      heroTitle: 'Four product series. One metrological discipline.',
      heroBody: 'Every model shown here is drawn from Xili’s official product leaflets — with the accuracy class, ratings and communication protocols as published.',
      seriesNote: 'Model numbers, accuracy classes and ratings as published in the official Xili product leaflets.',
      categories: [
        {
          slug: 'metering-instruments',
          name: 'Metering instruments',
          tagline: 'Measurement the grid can audit.',
          description: 'AC and DC smart electricity meters for State Grid and China Southern Power Grid specifications, acquisition terminals and dual-mode communication modules.',
          longText: 'This is the core of Xili’s business and the reason State Grid has rated the company a Grade-A supplier in every performance review since 2019. AC and DC meters, acquisition terminals and the HPLC+HRF modules that carry their data are engineered as one system — precise measurement, remote payment control, event logging and encrypted transport, from a single household to a whole distribution area.',
          items: [
            ['Smart electricity meters', 'Single- and three-phase AC meters in Class A, B and C for both national grid specifications, plus Class 0.5/1 DC energy meters to 1000 V and 600 A for charging piles, PV and telecom towers.'],
            ['Smart water meters', 'Remote-reading, valve-control and ultrasonic water meters over NB-IoT and LoRa, read alongside electricity.'],
            ['Terminals and modules', 'Energy controllers, fusion terminals, concentrators and dual-mode HPLC+HRF communication modules.'],
          ],
          points: ['Grade-A State Grid supplier since 2019', 'DL/T 698.45 and DL/T 645 protocol families', 'HPLC+HRF dual-mode communications'],
        },
        {
          slug: 'metering-transformers',
          name: 'Metering transformers',
          tagline: 'The first link in the measurement chain.',
          description: 'Current, voltage and combined instrument transformers from 0.66 kV to 35 kV, in accuracy classes 0.2S and 0.5S.',
          longText: 'A meter is only as accurate as the transformer feeding it. Xili develops and manufactures its own current, voltage and combined instrument transformers on dedicated lines, and calibrates them in the company’s own CNAS-accredited laboratory (CNAS L9323). The transformer and the meter are verified to the same documented standard, so the accuracy class covers the whole measurement chain rather than one instrument in it.',
          items: [
            ['Low-voltage current transformers', 'Class 0.2S/0.5S at 0.66 kV, ratios from 75/5 A to 3000/5 A.'],
            ['Medium-voltage current and voltage transformers', 'Epoxy dry-type units for 10–35 kV systems, anti-pollution design.'],
            ['Combined transformers', 'VT and CT in one enclosure for direct high-voltage energy metering.'],
          ],
          points: ['Accuracy classes 0.2S and 0.5S', 'In-house R&D and manufacturing', 'Transformer calibration in the CNAS-accredited laboratory (L9323)'],
        },
        {
          slug: 'distribution-network',
          name: 'Distribution network',
          tagline: 'The equipment that guards the metering point.',
          description: 'Metering enclosures, smart low-voltage distribution cabinets and pole-mounted circuit breakers by Zhejiang Xili Intelligent Technology.',
          longText: 'Zhejiang Xili Intelligent Technology, a wholly-owned subsidiary, builds the hardware that houses and protects the measurement point: metering enclosures in PC+ABS, SMC and stainless steel, integrated low-voltage distribution cabinets, and primary–secondary integrated pole-mounted breakers. Its own mould centre, injection machines and CNC lines keep tooling and consistency in-house.',
          items: [
            ['Metering enclosures', 'Single- and three-phase enclosures to Q/GDW 11008-2013 in composite or stainless steel.'],
            ['Distribution cabinets', 'Wall-mounted distribution boxes and pole-side integrated smart LV cabinets.'],
            ['Pole-mounted switchgear', 'ZW32 primary–secondary integrated breakers with measurement, protection and telecontrol.'],
          ],
          points: ['Q/GDW 11008-2013 metering enclosures', 'In-house mould centre and injection lines', 'ISO 9001 · 14001 · 45001 · 50001'],
        },
        {
          slug: 'new-energy',
          name: 'Energy storage',
          tagline: 'Stored where it is worth most.',
          description: 'Portable power stations and off-grid solar home systems by Zhejiang Xili New Energy, built on distributed-storage and microgrid research.',
          longText: 'Zhejiang Xili New Energy, capitalised at ¥50 million, works on distributed storage and microgrid technology — from portable stations for field and household backup to home and commercial-industrial storage. It draws on the group’s provincial technology centre and CNAS laboratory, and builds under ISO 9001, 14001 and 45001.',
          items: [
            ['Portable power stations', '288 Wh to 1,076 Wh with AC, DC, USB output and solar charging.'],
            ['Off-grid solar systems', '50 Wp solar home systems with PAYGO metering for off-grid lighting and charging.'],
            ['Home & commercial storage', 'Distributed storage for peak shaving, backup power and self-consumption.'],
          ],
          points: ['Distributed storage and microgrid technology', 'Backed by the group’s CNAS laboratory', 'ISO 9001 · 14001 · 45001'],
        },
      ],
    },
    solutions: {
      title: 'Solutions',
      heroTitle: 'Systems that move energy forward.',
      heroBody: 'Five solution directions — grid, integrated energy, commercial, apartment and campus — connected by one precise energy language.',
      items: [
        {
          slug: 'grid-intelligence',
          name: 'Grid intelligence',
          tagline: 'A more visible grid edge.',
          description: 'Smart metering, electricity-data acquisition and energy metering systems for utilities and grid operators.',
          longText: 'Grid intelligence starts at the measurement point. Xili combines smart meters, acquisition terminals and metering-box systems into deployments that give operators an accurate, continuous view of the grid edge.',
          points: [
            ['Accurate measurement', 'Metering products engineered to the accuracy classes utility programmes demand.'],
            ['Connected acquisition', 'Terminals and concentrators that move electricity data reliably into utility systems.'],
            ['Deployment experience', 'A metering heritage measured in decades, applied to modern rollout programmes.'],
          ],
          steps: ['Assess the metering landscape', 'Configure products and communications', 'Deploy and verify at scale', 'Support the installed base'],
        },
        {
          slug: 'pv-storage-charging',
          name: 'PV · Storage · Charging',
          tagline: 'One integrated energy loop.',
          description: 'A documented integrated direction for photovoltaic generation, energy storage and charging.',
          longText: 'Generation, storage and charging are one system, not three. This direction integrates PV input, energy storage and charging loads under coherent measurement and control — so energy flows where it is needed, when it is worth most.',
          points: [
            ['Generation-aware storage', 'Storage sized and controlled around real PV production profiles.'],
            ['Charging integration', 'Charging loads managed as part of the energy loop, not an afterthought.'],
            ['Measured everywhere', 'Xili metering discipline applied across every flow in the system.'],
          ],
          steps: ['Profile generation and loads', 'Design the integrated system', 'Install and commission', 'Operate with full visibility'],
        },
        {
          slug: 'commercial-energy',
          name: 'Commercial energy management',
          tagline: 'Energy as an operating advantage.',
          description: 'An integrated energy-management direction for industrial and commercial needs.',
          longText: 'For industrial and commercial sites, energy is a controllable cost and a resilience question. This direction combines measurement, storage and management so operators can see consumption clearly and act on it confidently. Deployed today in technology parks, office buildings, enterprises and shopping complexes: access, electricity and water read and controlled from one console, WeChat and app clients for balance top-up and fault reporting, and a cloud platform open to multi-party integration.',
          points: [
            ['Visibility first', 'Granular measurement across feeders, loads and time.'],
            ['Storage where it pays', 'Commercial storage applied to peak, backup and self-consumption value.'],
            ['Management in one loop', 'Data, storage and control working as one system.'],
          ],
          steps: ['Audit energy flows', 'Model the value case', 'Deploy measurement and storage', 'Manage and optimise'],
        },
        {
          slug: 'apartment-energy',
          name: 'Apartment energy management',
          tagline: 'Rental housing, running on one platform.',
          description: 'A smart hardware-and-software system for centralised, distributed and co-living apartments — contracts, rent and utilities managed in one place.',
          longText: 'The apartment solution gives operators one console for the whole rental business: contracts, rent and agency property services alongside smart devices — door locks, electricity, water and gas — with automated reading, statistics, remote control and resident announcements. Tenants use the app or WeChat client to check and top up rent and utilities, unlock doors remotely and report faults. The cloud platform stays open for multi-party integration across the smart-apartment ecosystem.',
          points: [
            ['One operator console', 'Contracts, rent, property services and smart-device data — read, counted and controlled in one place.'],
            ['A tenant app that answers', 'Rent and utility balances, top-ups, remote door locks, hardware control and one-tap fault reporting.'],
            ['An open cloud platform', 'Multi-party integration for the apartment ecosystem — operators, owners and service partners.'],
          ],
          steps: ['Survey the rental portfolio', 'Install smart locks, meters and sensors', 'Connect the console and tenant apps', 'Operate, settle and grow'],
        },
        {
          slug: 'campus-energy',
          name: 'Campus energy management',
          tagline: 'Utilities on campus, clearly managed.',
          description: 'An integrated water-and-electricity management solution for schools and campuses — smart hardware, IoT communications, cloud platform and mobile clients in one system.',
          longText: 'Built on Xili’s own smart meters, water meters and concentrators, the campus solution gives administrators one platform for both utilities: remote reading and remote valve or switch control, prepaid billing with automatic reminders, and safety policies such as scheduled power windows and overload protection for dormitories and teaching buildings.',
          points: [
            ['Remote reading & control', 'Electricity and water read remotely on one platform, with remote switch and valve control by room or building.'],
            ['Prepaid & automated billing', 'Prepaid accounts, automatic low-balance reminders and clear settlement for every dormitory.'],
            ['Safety by policy', 'Scheduled supply windows, overload and malicious-load protection designed for student housing.'],
          ],
          steps: ['Survey campus water and power', 'Deploy smart meters and concentrators', 'Connect the cloud platform and apps', 'Operate, bill and optimise'],
        },
      ],
    },
    technology: {
      title: 'Technology',
      heroTitle: 'Precision is an operating system.',
      heroBody: 'Research and production run as one system: an R&D team of over 100 across a provincial key enterprise research institute and a provincial enterprise technology centre, and a provincial-level smart factory in Deqing with 34 automated lines, 270+ items of high-end intelligent equipment and an annual capacity above ten million smart meters and terminals.',
      sectionTitle: 'R&D and digital management',
      sectionBody: 'Development capability and manufacturing capability are managed on one platform. Since 2012 Xili has driven a systematic digital and intelligent transformation across both — so that quality is measured, not assumed.',
      list: [
        ['A layered R&D and test platform', 'A provincial key enterprise research institute, a high-tech enterprise R&D centre, a provincial enterprise technology centre and a CNAS-accredited test centre, staffed by an R&D team of over 100.'],
        ['Eight core technology systems', 'From high-reliability data-storage middleware to modular software design and high-precision metrology.'],
        ['Research partnerships', 'Repeated participation in drafting national and industry standards; projects selected for the National Torch Programme; joint research with the University of Hong Kong, Hangzhou Dianzi University and Zhejiang University of Science and Technology.'],
        ['Digital management platform', 'Informatisation began in 2005 and now joins ERP, MES, PLM, EMS, EHR and the State Grid NQI supplier-side data system into one managed path from R&D to delivery.'],
      ],
      note: 'Built for reliable deployment across modern energy infrastructure.',
      twinIndex: 'Digital twin',
      twinTitle: 'The factory, mirrored in data.',
      twinBody: 'Lines, warehousing and test benches feed one live digital model of the plant — the same telemetry that drives MES scheduling renders the hall as a living twin, where every machine can be watched, simulated and improved.',
      twinTags: ['SMT & assembly lines', 'Automated verification', 'AS/RS warehouse', 'AGV logistics'],
      aiIndex: 'AI & intelligence',
      aiTitle: 'AI works the line beside us.',
      aiBody: 'Xili’s AI-and-manufacturing integration was selected as a provincial and national model case. Intelligence is not a pilot project here — it is embedded in inspection, scheduling and everyday operations.',
      aiList: [
        ['Large-model applications', 'AI large models embedded in quality analytics, production knowledge and operations workflows — answers drawn from the factory’s own data.'],
        ['Machine-vision inspection', 'Vision systems inspect boards and assemblies inline, catching defects at line speed before they travel downstream.'],
        ['AI-assisted scheduling', 'Algorithms plan across 34 lines and 270+ machines, balancing tender deadlines against capacity in the MES.'],
        ['Digital operations platform', 'Company-wide operations rendered visual and data-driven — live since 2024, from order to delivery.'],
      ],
      labsIndex: 'Laboratories',
      labsTitle: 'Automated laboratories, around the clock.',
      labsBody: 'Xili’s testing centre is accredited by CNAS, the China National Accreditation Service for Conformity Assessment (CNAS L9323). Meters, instrument transformers and terminals are calibrated, stress-tested and certified here on automated benches that do not stop between shifts. Twenty consecutive years of passing national and provincial quality supervision checks rest on verification the company runs itself.',
      labsList: [
        ['Automated verification & calibration', 'Robotic benches verify meters and instrument transformers against reference standards — high-volume, operator-light, audit-ready.'],
        ['Reliability & environmental testing', 'Temperature, humidity, surge and life-cycle chambers prove products against years of field stress.'],
        ['EMC & electrical safety', 'Electromagnetic-compatibility and safety benches qualify products for grid environments and export markets.'],
        ['Energy-storage testing', 'Cell and pack benches cycle, load and abuse-test storage products across the full temperature window.'],
      ],
      ipIndex: 'Standards & IP',
      ipTitle: 'Written into the standards.',
      ipStats: [
        [132, '', 'Patents granted'],
        [27, '', 'Invention patents'],
        [148, '', 'Software copyrights'],
        [42, '', 'National, industry & group standards co-drafted'],
      ],
      ipNote: 'Recognition includes the China Patent Excellence Award (2018), the China Invention & Entrepreneurship Achievement Award, second class (2025), and selection of the DJTD23-XL31102 concentrator as a 2025 “Made in Zhejiang” premium product.',
      milestonesTitle: 'Engineering milestones',
      milestones: [
        ['2005', 'Informatisation begins', 'ERP, MES and PLM systems come online as one managed platform.'],
        ['2012', 'Digital transformation', 'A systematic digital and intelligent overhaul of the manufacturing system starts.'],
        ['2023', 'Deqing park in production', 'Digital workshops and automated warehousing across a 120,000 m² intelligent park.'],
        ['2025', 'AI-enabled manufacturing', 'Deep AI-manufacturing integration, selected as a provincial and national model case.'],
      ],
    },
    about: {
      title: 'About us',
      heroTitle: 'From a four-person pump station to the STAR Market.',
      heroBody: 'Xili traces back to the Hangzhou Watt-Hour Meter Factory, founded in 1968. In 1999 it was restructured as Hangzhou Xili Electric Energy Meter Manufacturing Co., Ltd.; in 2016 it converted to a joint-stock company; and on 18 March 2021 it listed on the STAR Market of the Shanghai Stock Exchange — the first smart-meter company to do so.',
      storyTitle: 'Nearly six decades, one conviction',
      storyBody: '“Quality first, technology leads to success” has carried Xili through nearly six decades — from mechanical meters to smart meters, from traditional manufacturing to AI-enabled production. Restructured as a private company in 1999, past the hundred-million-yuan revenue mark in 2010, listed on the STAR Market in 2021, and now running a provincial-level smart factory in the Deqing science park. Alongside electricity meters, acquisition terminals and metering enclosures, the company applies the same metering-plus-communications discipline to EV and e-bike charging measurement, 5G base-station energy monitoring and smart water meters. Today Xili runs 34 automated production lines with 270+ items of high-end intelligent equipment and automated warehousing — an annual capacity above ten million meters and terminals — serving 500+ clients across 33 provincial-level regions, with products passing national and provincial quality supervision checks for twenty consecutive years.',
      globalIndex: 'Global footprint',
      globalTitle: 'Measured at home. Trusted abroad.',
      globalBody: 'Xili serves 500+ clients across all 33 provincial-level regions of China, and ships metering products to export markets across Southeast Asia, Africa, Eastern Europe and South America. The company is a member of the DLMS User Association (Switzerland) and the STS Association (South Africa) — the two standards bodies that govern how the world’s meters communicate and prepay.',
      globalHub: 'Hangzhou',
      globalMarkets: ['Thailand', 'Bangladesh', 'South Korea', 'Philippines', 'Eastern Europe', 'Ghana', 'Chile', 'Ecuador', 'Pakistan'],
      globalStats: [
        [33, '', 'Provinces & regions in China'],
        [10, '', 'Export markets'],
        [24, '', 'Long-term partners'],
      ],
      investorIndex: 'Investor relations',
      investorTitle: 'Listed. Audited. Dividend-paying.',
      investorStats: [
        ['¥566M', 'Revenue · FY2025'],
        ['¥104M', 'Net profit · FY2025'],
        ['5.5%', 'Of revenue into R&D'],
        ['50.9%', 'Dividend payout ratio'],
      ],
      investorNote: 'Hangzhou Xili Intelligent Technology Co., Ltd. — 688616.SH, STAR Market, Shanghai Stock Exchange. Audited by Pan-China CPAs with an unqualified opinion. Investor relations: zqb@cnxili.com',
      subsidiariesIndex: 'Group structure',
      subsidiariesTitle: 'Two wholly-owned subsidiaries.',
      subsidiaries: [
        ['Zhejiang Xili Intelligent Technology', 'Smart distribution equipment', 'A core supplier of smart metering enclosures, integrated low-voltage distribution cabinets, cable branch boxes and primary–secondary integrated pole-mounted breakers. Runs its own injection moulding, CNC machining, EDM and automated assembly lines, a municipal R&D centre and a provincial enterprise research institute, under ISO 9001, 14001, 45001 and 50001. Named a Zhejiang Smart Factory in 2023.'],
        ['Zhejiang Xili New Energy', 'Distributed energy storage', 'Capitalised at ¥50 million and focused on distributed storage and microgrid technology. Develops and manufactures portable power stations, off-grid solar home systems, home storage and commercial-industrial storage, drawing on the group’s provincial technology centre and CNAS laboratory. ISO 9001, 14001 and 45001. Brand promise: “Xili power — green and safe.”'],
      ],
      valuesTitle: 'Corporate culture',
      valuesLede: 'Since its founding Xili has held to a development philosophy of “quality first, technology leads to success” and a management philosophy of “dedication, discipline, standards, precision”, carried out under one requirement: execution above all, details decide the outcome. Technological innovation and honest dealing guide how strategy is planned, how rules are set, and how people are developed.',
      values: [
        ['Mission', 'Advance energy metering; serve every user.'],
        ['Vision', 'To become the leader of China’s electrical instrument industry — and a respected enterprise.'],
        ['Core values', 'Customer first. Management excellence.'],
        ['Operating principle', 'Technological innovation and honest dealing.'],
        ['Management philosophy', 'Dedication, discipline, standards, precision.'],
        ['Development philosophy', 'Quality first; technology leads to success.'],
      ],
      timelineTitle: 'Milestones',
      timeline: [
        ['1968', 'Founded', 'Started as a 3–4 person irrigation pump station of the West Lake Agricultural Machinery Factory.'],
        ['1999', 'Privatised', 'Shareholding reform completed; renamed Hangzhou Xili Electric Energy Meter Manufacturing.'],
        ['2010', '¥100M revenue', 'Annual revenue passed one hundred million yuan after strong State Grid tender results.'],
        ['2016', 'Joint-stock reform', 'Renamed Hangzhou Xili Intelligent Technology Co., Ltd.; modern governance in place.'],
        ['2021', 'STAR Market listing', 'Listed on 18 March 2021 (688616) — first listed company in the smart-meter industry on the STAR Market.'],
        ['2023', 'Deqing park online', 'The 120,000 m² intelligent industrial park entered full production with digital workshops and automated warehousing.'],
        ['2024', 'Record results', 'Net profit reached a record ¥104 million; digital operations platform went live.'],
        ['2025', 'AI in manufacturing', 'AI-manufacturing integration selected as a provincial and national model case; new-energy revenue up 281% year on year.'],
      ],
      honorsTitle: 'Honors & qualifications',
      honorStats: [
        [132, '', 'Patents granted'],
        [148, '', 'Software copyrights'],
        [42, '', 'Standards co-drafted'],
        [40, '+', 'Certified S&T achievements'],
      ],
      honors: [
        'State Grid supplier rating: Grade A in every review since 2019',
        'China Well-Known Trademark',
        'National High-Tech Enterprise',
        'National Green Factory (MIIT, 2025)',
        'National Intellectual Property Creation Enterprise',
        'CNAS-accredited testing centre (CNAS L9323)',
        'Provincial Hidden Champion enterprise (2025)',
        'Provincial Key Enterprise Research Institute (2025)',
        'Provincial Key Industrial Internet Platform (2026)',
        'Zhejiang specialised & innovative SME',
        'Zhejiang Manufacturing certification · China Energy-Saving Product certification',
        'ISO 10012 measurement management system',
        'ISO 27001 information security management system',
        'ISO 9001 · 14001 · 45001 · 50001 management systems',
        'IP management and social-responsibility management systems',
        'Product carbon-footprint certificates for instrument transformers',
        'Green design product management system, AAAAA',
        'Green supply chain and greenhouse-gas management systems',
        'Zhejiang Science and Technology Progress Award',
        'National Invention & Entrepreneurship Award',
        'China Patent Excellence Award (2018)',
        'Member, DLMS User Association · STS Association',
        'First STAR-Market-listed smart-meter company',
      ],
      csrTitle: 'Responsibility',
      csr: [
        ['Green, low-carbon manufacturing', 'Green process upgrades since 2014, with provincial environmental innovation awards; ongoing carbon verification and footprint certification in support of dual-carbon goals.'],
        ['Accountable governance', 'Quality, environment, occupational health & safety and information-security management systems — with an annual ESG report disclosing practice and performance.'],
        ['Community & care', 'A dedicated charity fund has supported 55 patients with ¥225,400 in aid by 2025, alongside pandemic-relief donations and staff blood-donation drives.'],
      ],
      officialAction: 'Official Xili Technology site',
      officialUrl: 'https://www.cnxili.com/en/WestForceProfile/index.aspx',
    },
    news: {
      title: 'News',
      heroTitle: 'News & milestones.',
      heroBody: 'Company announcements and the milestones that shaped Xili — updated as the story continues.',
      items: [
        ['2026', 'Contracts', 'State Grid tender wins exceed ¥162 million', 'Xili was named a winning bidder in State Grid’s 2026 first metering-equipment tender — Class-A single-phase and Class-B/C three-phase smart meters, smart fusion terminals and metering instrument transformers — worth ¥162 million in total, with further wins in Hubei, Anhui, Heilongjiang and Shanghai.', 'meter-line'],
        ['2026', 'ESG', '2025 ESG reports published', 'Hangzhou Xili and Zhejiang Xili published their 2025 environmental, social and governance reports, extending disclosure across both the metering and new-energy businesses.', 'pv-solution'],
        ['2026', 'Results', 'FY2025: steady profit and a ¥52.9M dividend', 'Revenue of ¥566 million with net profit of ¥104 million and operating cash flow up 53%. A ¥3-per-10-shares dividend returns 50.9% of net profit to shareholders.', 'zhuantang-hq'],
        ['2026', 'Manufacturing', 'Future-factory upgrade selected as a Zhejiang demonstration project', 'The smart energy-metering terminal future-factory retrofit was selected for Zhejiang Province’s 2026 production-mode transformation demonstration list.', 'robot-cell'],
        ['2026', 'Recognition', 'Named a national-level Green & Low-Carbon Factory', 'Xili Technology was awarded the national Green & Low-Carbon Factory designation, recognising energy-efficient, low-emission manufacturing across its parks.', 'deqing-park'],
        ['2025', 'Milestone', 'AI-manufacturing integration named a national model case', 'Xili’s deep integration of AI and manufacturing was selected as a provincial and national model case; Xili New Energy revenue grew 281% year on year.', 'robot-glow'],
        ['2024', 'Results', 'Record net profit of ¥104 million', 'Full-year net profit reached a record ¥104 million; the digital operations platform went live, bringing visual, data-driven management across the company.', 'hall'],
        ['2023', 'Manufacturing', 'Deqing intelligent industrial park in full production', 'The 120,000 m² park entered full production, with digital workshops and automated warehousing online.', 'campus-aerial'],
        ['2021', 'Milestone', 'Xili Technology lists on the STAR Market', 'Hangzhou Xili Intelligent Technology (688616.SH) lists on the STAR Market of the Shanghai Stock Exchange — a public commitment to precision engineering.', 'listing-2021'],
        ['2005', 'Manufacturing', 'The digital factory journey begins', 'Xili connects product lifecycle, manufacturing execution and equipment data into one loop — quality measured, not assumed.', 'factory-2005'],
        ['1968', 'Heritage', 'The metering heritage begins', 'The industrial foundation in electricity metering that still anchors Xili’s accuracy culture today.', 'heritage-1968'],
      ],
      note: 'Further announcements are published after official verification.',
    },
    careers: {
      title: 'Careers',
      heroTitle: 'Build the instruments the grid relies on.',
      heroBody: 'Precision work needs precise people. Join a team where measurement is a craft and energy is the mission.',
      whyTitle: 'Why Xili',
      why: [
        ['Real infrastructure', 'Your work ships into grids, factories and homes — measured in decades, not sprints.'],
        ['Engineering depth', 'Metrology, power electronics, communications and manufacturing systems under one roof.'],
        ['A listed platform', 'The stability of a STAR-Market-listed company with the focus of a specialist.'],
      ],
      areasTitle: 'Hiring directions',
      areas: [
        ['R&D engineering', 'Metering, storage, embedded and communications engineering.'],
        ['Manufacturing & supply chain', 'Digital-factory operations, process and equipment engineering.'],
        ['Quality & testing', 'Metrology-grade verification from line to laboratory.'],
        ['Market & sales', 'Utility programmes and international market development.'],
      ],
      action: 'Introduce yourself',
      note: 'Send your CV and the direction you’re interested in — we reply to every serious application.',
    },
    contact: {
      title: 'Contact',
      heroTitle: 'Let’s make energy more legible.',
      heroBody: 'Tell us where your energy system needs more precision, visibility or resilience.',
      action: 'Start a conversation',
      channelsTitle: 'Reach us',
      email: 'hzxilidb@cnxili.com',
      offices: 'Hangzhou · Deqing · China',
      officeTitle: 'Locations',
      locations: [
        ['zhuantang-hq', 'Headquarters · Hangzhou', 'No. 173 Liangfu Road, Zhuantang, Xihu District, Hangzhou 310024, Zhejiang, China · +86 571 87825461 / 56660360'],
        ['deqing-park', 'Manufacturing base · Deqing', 'No. 733 North Huancheng Road, Deqing County, Huzhou 313000, Zhejiang, China · +86 572 8233298 / 8233258'],
      ],
      emailTitle: 'Email',
      responseNote: 'We reply to solution enquiries within two business days.',
    },
    footer: {
      descriptor: 'Smart energy intelligence',
      colProducts: 'Products',
      colSolutions: 'Solutions',
      colCompany: 'Company',
      legal: '© 2026 Xili Technology. All rights reserved.',
    },
  },

  fr: {
    locale: 'FR',
    code: 'fr',
    meta: {
      title: 'Xili Technology — Intelligence énergétique',
      description: 'Une intelligence énergétique fondée sur la précision, de la mesure jusqu’au stockage résilient.',
    },
    common: {
      home: 'Accueil',
      explore: 'Explorer',
      learnMore: 'En savoir plus',
      viewAll: 'Tout voir',
      backTo: 'Retour à',
      discuss: 'Échanger sur une solution',
      contactUs: 'Nous contacter',
      menu: 'Menu',
      close: 'Fermer le menu',
      related: 'À découvrir',
      keyPoints: 'Capacités clés',
      process: 'Notre démarche',
      categories: 'Lignes de produits',
      directions: 'Orientations de solution',
      scroll: 'Défiler',
      breadcrumbProducts: 'Produits',
      breadcrumbSolutions: 'Solutions',
      imageSoon: 'Visuel à venir',
      readMore: 'Lire la suite',
    },
    nav: {
      products: 'Produits',
      solutions: 'Solutions',
      technology: 'Technologie',
      about: 'À propos',
      news: 'Actualités',
      careers: 'Nous recrutons',
      contact: 'Contact',
    },
    marquee: ['Comptage intelligent', 'Données de réseau', 'Réseau de distribution', 'Stockage d’énergie', 'Gestion numérique', 'Ingénierie de précision'],
    home: {
      heroKicker: 'La qualité d’abord · La technologie l’emporte',
      heroTitle: 'Compteurs intelligents. Réseaux de distribution. Stockage d’énergie.',
      heroBody: 'Hangzhou Xili conçoit des systèmes de mesure électrique, des équipements de réseau de distribution et des systèmes de stockage de qualité réseau — du comptage intelligent au stockage commercial. Cotée au STAR Market depuis 2021.',
      heroPrimary: 'Explorer les produits',
      heroSecondary: 'Découvrir Xili',
      stats: [
        [1968, '', 'Fondation'],
        [2021, '', 'Cotation au STAR Market'],
        [500, '+', 'Clients servis'],
        [33, '', 'Provinces et régions couvertes'],
      ],
      pillarsIndex: 'Présentation',
      pillarsTitle: 'Une seule couche d’intelligence. Trois capacités essentielles.',
      pillarsBody: 'Xili réunit mesure électrique, équipements de réseau de distribution et stockage dans un portefeuille énergétique cohérent.',
      pillars: [
        ['01', 'Comptage intelligent', 'Une mesure électrique précise à chaque point du réseau.'],
        ['02', 'Réseau de distribution', 'Coffrets, armoires BT et disjoncteurs sur poteau autour du point de mesure.'],
        ['03', 'Stockage d’énergie', 'Des systèmes distribués, du portable à l’échelle commerciale.'],
      ],
      productsIndex: 'Produits',
      productsTitle: 'Un portefeuille construit autour de la chaîne énergétique.',
      productsBody: 'Trois lignes de produits couvrant la mesure, la distribution et le stockage — chacune avec sa propre présentation.',
      solutionsIndex: 'Solutions',
      solutionsTitle: 'Des systèmes qui font avancer l’énergie.',
      solutionsBody: 'Cinq orientations de solution — réseau, énergie intégrée, commercial, résidentiel locatif et campus — connectées par un langage énergétique précis.',
      technologyIndex: 'Technologie',
      technologyTitle: 'La précision est un système d’exploitation.',
      technologyBody: 'Une équipe R&D de plus de 100 personnes et un institut de recherche clé provincial, alimentant 34 lignes automatisées sur une même plateforme de gestion numérique — du développement à la livraison.',
      technologyAction: 'Au cœur de la R&D et de la fabrication',
      newsIndex: 'Actualités',
      newsTitle: 'Dernières nouvelles de Xili.',
      partnersIndex: 'Partenaires',
      partnersTitle: 'La confiance de toute la chaîne énergétique.',
      partnersBody: 'Gestionnaires de réseau, leaders des énergies nouvelles et partenaires amont et aval de la chaîne d’approvisionnement de Xili.',
      zhFirst: false,
      ctaTitle: 'Rendons l’énergie plus lisible.',
      ctaBody: 'Indiquez-nous où votre système énergétique a besoin de plus de précision, de visibilité ou de résilience.',
    },
    products: {
      title: 'Produits',
      catalogIndex: 'Catalogue produits',
      heroTitle: 'Quatre séries de produits. Une seule discipline métrologique.',
      heroBody: 'Chaque modèle présenté ici provient des dépliants produits officiels de Xili — avec la classe de précision, les calibres et les protocoles de communication tels que publiés.',
      seriesNote: 'Références, classes de précision et calibres tels que publiés dans les dépliants produits officiels de Xili.',
      categories: [
        {
          slug: 'metering-instruments',
          name: 'Instruments de comptage',
          tagline: 'Une mesure que le réseau peut auditer.',
          description: 'Compteurs électriques intelligents CA et CC aux spécifications State Grid et China Southern Power Grid, terminaux d’acquisition et modules de communication bimode.',
          longText: 'C’est le cœur de l’activité de Xili et la raison pour laquelle State Grid classe l’entreprise fournisseur de classe A à chaque évaluation depuis 2019. Compteurs CA et CC, terminaux d’acquisition et modules HPLC+HRF qui transportent leurs données sont conçus comme un seul système : mesure précise, prépaiement à distance, journalisation des événements et transport chiffré, du foyer isolé au quartier entier.',
          items: [
            ['Compteurs électriques intelligents', 'Compteurs CA mono- et triphasés en classes A, B et C pour les deux spécifications nationales, et compteurs CC classes 0,5 et 1 jusqu’à 1000 V et 600 A pour bornes de recharge, PV et pylônes télécom.'],
            ['Compteurs d’eau intelligents', 'Télérelevé, vanne pilotée et mesure ultrasonique via NB-IoT et LoRa, relevés avec l’électricité.'],
            ['Terminaux et modules', 'Contrôleurs d’énergie, terminaux de fusion, concentrateurs et modules bimode HPLC+HRF.'],
          ],
          points: ['Fournisseur State Grid classe A depuis 2019', 'Familles de protocoles DL/T 698.45 et DL/T 645', 'Communications bimode HPLC+HRF'],
        },
        {
          slug: 'metering-transformers',
          name: 'Transformateurs de mesure',
          tagline: 'Le premier maillon de la chaîne de mesure.',
          description: 'Transformateurs de courant, de tension et combinés de 0,66 kV à 35 kV, en classes de précision 0,2S et 0,5S.',
          longText: 'Un compteur n’est jamais plus précis que le transformateur qui l’alimente. Xili développe et fabrique ses propres transformateurs de courant, de tension et combinés sur lignes dédiées, puis les étalonne dans son propre laboratoire accrédité CNAS (CNAS L9323). Le transformateur et le compteur sont vérifiés selon la même référence documentée : la classe de précision couvre toute la chaîne de mesure, et non un seul instrument.',
          items: [
            ['Transformateurs de courant BT', 'Classes 0,2S/0,5S à 0,66 kV, rapports de 75/5 A à 3000/5 A.'],
            ['Transformateurs MT de courant et de tension', 'Unités sèches époxy pour réseaux 10–35 kV, conception anti-pollution.'],
            ['Transformateurs combinés', 'TT et TC dans une même enveloppe pour le comptage direct en haute tension.'],
          ],
          points: ['Classes de précision 0,2S et 0,5S', 'R&D et fabrication en interne', 'Étalonnage des transformateurs au laboratoire accrédité CNAS (L9323)'],
        },
        {
          slug: 'distribution-network',
          name: 'Réseau de distribution',
          tagline: 'Le coffret autour du compteur.',
          description: 'Coffrets de comptage, armoires BT intelligentes et disjoncteurs sur poteau par Zhejiang Xili Intelligent Technology.',
          longText: 'Zhejiang Xili Intelligent Technology, filiale à 100 %, fabrique le matériel qui abrite et protège le point de mesure : coffrets de comptage en PC+ABS, SMC et acier inoxydable, armoires BT intégrées et disjoncteurs sur poteau à intégration primaire-secondaire. Son propre centre de moules, ses presses à injecter et ses centres d’usinage gardent l’outillage et la constance en interne.',
          items: [
            ['Coffrets de comptage', 'Coffrets mono- et triphasés selon Q/GDW 11008-2013, en composite ou acier inoxydable.'],
            ['Armoires de distribution', 'Coffrets muraux et armoires BT intelligentes installées près du transformateur.'],
            ['Appareillage sur poteau', 'Disjoncteurs ZW32 à intégration primaire-secondaire avec mesure, protection et télécontrôle.'],
          ],
          points: ['Coffrets Q/GDW 11008-2013', 'Centre de moules et lignes d’injection internes', 'ISO 9001 · 14001 · 45001 · 50001'],
        },
        {
          slug: 'new-energy',
          name: 'Stockage d’énergie',
          tagline: 'Stockée là où elle vaut le plus.',
          description: 'Stations d’énergie portables et systèmes solaires domestiques hors réseau par Zhejiang Xili New Energy, adossés à la recherche en stockage distribué et microréseaux.',
          longText: 'Zhejiang Xili New Energy, dotée d’un capital de 50 millions de yuans, travaille sur le stockage distribué et les microréseaux — des stations portables pour le terrain et le secours domestique jusqu’au stockage résidentiel et commercial. Elle s’appuie sur le centre technologique provincial et le laboratoire CNAS du groupe, et produit sous ISO 9001, 14001 et 45001.',
          items: [
            ['Stations d’énergie portables', 'De 288 Wh à 1 076 Wh avec sorties CA, CC, USB et charge solaire.'],
            ['Systèmes solaires hors réseau', 'Systèmes solaires domestiques 50 Wc avec comptage PAYGO, pour l’éclairage et la recharge hors réseau.'],
            ['Stockage résidentiel et commercial', 'Stockage distribué pour l’écrêtage de pointe, le secours et l’autoconsommation.'],
          ],
          points: ['Stockage distribué et technologies de microréseau', 'Adossé au laboratoire CNAS du groupe', 'ISO 9001 · 14001 · 45001'],
        },
      ],
    },
    solutions: {
      title: 'Solutions',
      heroTitle: 'Des systèmes qui font avancer l’énergie.',
      heroBody: 'Cinq orientations de solution — réseau, énergie intégrée, commercial, résidentiel locatif et campus — connectées par un langage énergétique précis.',
      items: [
        {
          slug: 'grid-intelligence',
          name: 'Intelligence réseau',
          tagline: 'Un réseau plus visible.',
          description: 'Comptage intelligent, acquisition de données et systèmes de mesure pour les gestionnaires de réseau.',
          longText: 'L’intelligence réseau commence au point de mesure. Xili combine compteurs, terminaux d’acquisition et coffrets de comptage en déploiements qui donnent aux opérateurs une vision précise et continue du réseau.',
          points: [
            ['Mesure précise', 'Des produits de comptage conçus pour les classes de précision exigées.'],
            ['Acquisition connectée', 'Des terminaux qui acheminent les données de façon fiable.'],
            ['Expérience de déploiement', 'Des décennies de comptage appliquées aux programmes modernes.'],
          ],
          steps: ['Évaluer le parc de comptage', 'Configurer produits et communications', 'Déployer et vérifier à l’échelle', 'Accompagner le parc installé'],
        },
        {
          slug: 'pv-storage-charging',
          name: 'PV · Stockage · Recharge',
          tagline: 'Une seule boucle énergétique.',
          description: 'Une orientation intégrée documentée pour le photovoltaïque, le stockage et la recharge.',
          longText: 'Production, stockage et recharge forment un seul système. Cette orientation intègre l’apport PV, le stockage d’énergie et les charges de recharge sous une mesure et un contrôle cohérents.',
          points: [
            ['Stockage lié à la production', 'Un stockage dimensionné sur les profils réels de production PV.'],
            ['Recharge intégrée', 'Des charges gérées comme partie de la boucle énergétique.'],
            ['Tout est mesuré', 'La discipline de comptage Xili appliquée à chaque flux.'],
          ],
          steps: ['Profiler production et charges', 'Concevoir le système intégré', 'Installer et mettre en service', 'Exploiter en pleine visibilité'],
        },
        {
          slug: 'commercial-energy',
          name: 'Gestion énergétique commerciale',
          tagline: 'L’énergie comme avantage opérationnel.',
          description: 'Une orientation de gestion énergétique intégrée pour les besoins industriels et commerciaux.',
          longText: 'Pour les sites industriels et commerciaux, l’énergie est un coût pilotable et une question de résilience. Cette orientation combine mesure, stockage et gestion pour agir en confiance. Déployée aujourd’hui dans les parcs technologiques, immeubles de bureaux, entreprises et centres commerciaux : accès, électricité et eau relevés et pilotés depuis une console unique, clients WeChat et mobile pour recharges et signalement de pannes, et une plateforme cloud ouverte à l’intégration multi-acteurs.',
          points: [
            ['La visibilité d’abord', 'Une mesure fine des départs, des charges et du temps.'],
            ['Le stockage là où il paie', 'Du stockage appliqué à l’écrêtage, au secours et à l’autoconsommation.'],
            ['Une seule boucle de gestion', 'Données, stockage et contrôle en un système.'],
          ],
          steps: ['Auditer les flux d’énergie', 'Modéliser le cas de valeur', 'Déployer mesure et stockage', 'Gérer et optimiser'],
        },
        {
          slug: 'apartment-energy',
          name: 'Gestion énergétique des résidences',
          tagline: 'Le locatif, piloté depuis une seule plateforme.',
          description: 'Un système matériel et logiciel intelligent pour résidences centralisées, diffuses et en colocation — contrats, loyers et fluides gérés au même endroit.',
          longText: 'La solution résidences offre aux exploitants une console unique pour toute l’activité locative : contrats, loyers et services de gestion, aux côtés des équipements intelligents — serrures connectées, électricité, eau et gaz — avec relevé automatisé, statistiques, commande à distance et annonces aux résidents. Les locataires utilisent l’application ou le client WeChat pour consulter et recharger loyers et fluides, ouvrir leur porte à distance et signaler une panne. La plateforme cloud reste ouverte à l’intégration multi-acteurs de l’écosystème.',
          points: [
            ['Une console exploitant', 'Contrats, loyers, services et données des équipements — relevés, comptés et pilotés au même endroit.'],
            ['Une application qui répond', 'Soldes de loyer et de fluides, recharges, serrures à distance et signalement de panne en un geste.'],
            ['Une plateforme cloud ouverte', 'Intégration multi-acteurs pour l’écosystème résidentiel — exploitants, propriétaires et partenaires.'],
          ],
          steps: ['Cartographier le parc locatif', 'Installer serrures, compteurs et capteurs', 'Connecter console et applications', 'Exploiter, facturer et développer'],
        },
        {
          slug: 'campus-energy',
          name: 'Gestion énergétique des campus',
          tagline: 'L’eau et l’électricité du campus, sous contrôle.',
          description: 'Une solution intégrée de gestion de l’eau et de l’électricité pour les écoles et campus — matériel intelligent, communications IoT, plateforme cloud et applications mobiles en un seul système.',
          longText: 'Bâtie sur les compteurs d’électricité, compteurs d’eau et concentrateurs de Xili, la solution campus offre aux gestionnaires une plateforme unique pour les deux fluides : télérelevé et commande à distance des vannes et interrupteurs, prépaiement avec relances automatiques, et politiques de sécurité — plages d’alimentation programmées, protection contre les surcharges — pour internats et bâtiments d’enseignement.',
          points: [
            ['Relevé et commande à distance', 'Électricité et eau relevées à distance sur une seule plateforme, avec commande par chambre ou bâtiment.'],
            ['Prépaiement et facturation automatisée', 'Comptes prépayés, relances automatiques de solde et règlement clair pour chaque dortoir.'],
            ['La sécurité par la règle', 'Plages horaires programmées, protection contre surcharges et charges interdites, pensées pour le logement étudiant.'],
          ],
          steps: ['Cartographier eau et électricité du campus', 'Déployer compteurs et concentrateurs', 'Connecter plateforme cloud et applications', 'Exploiter, facturer et optimiser'],
        },
      ],
    },
    technology: {
      title: 'Technologie',
      heroTitle: 'La précision est un système d’exploitation.',
      heroBody: 'Recherche et production forment un seul système : une équipe R&D de plus de 100 personnes répartie entre un institut de recherche d’entreprise clé provincial et un centre technologique provincial, et une usine intelligente de niveau provincial à Deqing — 34 lignes automatisées, plus de 270 équipements intelligents de haut niveau et une capacité annuelle de plus de dix millions de compteurs et terminaux.',
      sectionTitle: 'R&D et gestion numérique',
      sectionBody: 'Capacité de développement et capacité de fabrication sont pilotées sur une même plateforme. Depuis 2012, Xili y mène une transformation numérique et intelligente systématique — pour que la qualité soit mesurée, jamais supposée.',
      list: [
        ['Une plateforme de R&D et d’essais à plusieurs niveaux', 'Un institut de recherche d’entreprise clé provincial, un centre de R&D d’entreprise de haute technologie, un centre technologique provincial et un centre d’essais accrédité CNAS, avec une équipe R&D de plus de 100 personnes.'],
        ['Huit systèmes technologiques fondamentaux', 'Du middleware de stockage de données à haute fiabilité à la conception logicielle modulaire et à la métrologie de haute précision.'],
        ['Partenariats de recherche', 'Participation répétée à la rédaction de normes nationales et sectorielles ; projets retenus au Programme national Torch ; recherches conjointes avec l’Université de Hong Kong, l’Université Dianzi de Hangzhou et l’Université des sciences et technologies du Zhejiang.'],
        ['Plateforme de gestion numérique', 'L’informatisation, engagée dès 2005, réunit aujourd’hui ERP, MES, PLM, EMS, EHR et le système NQI côté fournisseur de State Grid en un seul parcours géré, de la R&D à la livraison.'],
      ],
      note: 'Conçu pour un déploiement fiable dans les infrastructures énergétiques modernes.',
      twinIndex: 'Jumeau numérique',
      twinTitle: 'L’usine, reflétée en données.',
      twinBody: 'Lignes, entrepôt et bancs d’essai alimentent un modèle numérique vivant de l’usine — la télémétrie qui pilote l’ordonnancement MES rend l’atelier sous forme de jumeau, où chaque machine s’observe, se simule et s’améliore.',
      twinTags: ['Lignes SMT et assemblage', 'Vérification automatisée', 'Entrepôt automatisé', 'Logistique AGV'],
      aiIndex: 'IA et intelligence',
      aiTitle: 'L’IA travaille sur la ligne, à nos côtés.',
      aiBody: 'L’intégration IA-fabrication de Xili a été retenue comme cas modèle provincial et national. L’intelligence n’est pas un projet pilote : elle est intégrée à l’inspection, à l’ordonnancement et à l’exploitation quotidienne.',
      aiList: [
        ['Applications de grands modèles', 'Des grands modèles d’IA intégrés à l’analyse qualité, au savoir industriel et aux flux d’exploitation — des réponses tirées des données de l’usine elle-même.'],
        ['Inspection par vision industrielle', 'Des systèmes de vision inspectent cartes et assemblages en ligne, au rythme de la production.'],
        ['Ordonnancement assisté par IA', 'Des algorithmes planifient sur 34 lignes et 270+ machines, en équilibrant délais d’appels d’offres et capacité dans le MES.'],
        ['Plateforme d’exploitation numérique', 'L’exploitation de toute l’entreprise rendue visuelle et pilotée par les données — en service depuis 2024.'],
      ],
      labsIndex: 'Laboratoires',
      labsTitle: 'Des laboratoires automatisés, jour et nuit.',
      labsBody: 'Le centre d’essais de Xili est accrédité CNAS, le service national chinois d’accréditation pour l’évaluation de la conformité (CNAS L9323). Compteurs, transformateurs de mesure et terminaux y sont étalonnés, éprouvés et certifiés sur des bancs automatisés qui ne s’arrêtent pas entre les équipes. Vingt années consécutives de contrôles qualité nationaux et provinciaux réussis reposent sur une vérification que l’entreprise mène elle-même.',
      labsList: [
        ['Vérification et étalonnage automatisés', 'Des bancs robotisés vérifient compteurs et transformateurs de mesure contre des étalons de référence — haut volume, prêt pour l’audit.'],
        ['Fiabilité et essais d’environnement', 'Chambres de température, d’humidité, de surtension et d’endurance : des années de contraintes terrain, condensées.'],
        ['CEM et sécurité électrique', 'Des bancs de compatibilité électromagnétique et de sécurité qualifient les produits pour le réseau et l’export.'],
        ['Essais de stockage d’énergie', 'Des bancs cellule et pack cyclent, chargent et éprouvent les produits de stockage sur toute la plage de température.'],
      ],
      ipIndex: 'Normes et PI',
      ipTitle: 'Écrit dans les normes.',
      ipStats: [
        [132, '', 'Brevets délivrés'],
        [27, '', 'Brevets d’invention'],
        [148, '', 'Droits d’auteur logiciels'],
        [42, '', 'Normes nationales, sectorielles et de groupe corédigées'],
      ],
      ipNote: 'Distinctions : Prix chinois de l’excellence en brevets (2018), Prix chinois de l’invention et de l’entrepreneuriat, 2e classe (2025), et concentrateur DJTD23-XL31102 sélectionné « Made in Zhejiang » premium 2025.',
      milestonesTitle: 'Jalons d’ingénierie',
      milestones: [
        ['2005', 'Début de l’informatisation', 'ERP, MES et PLM entrent en service comme une plateforme unique.'],
        ['2012', 'Transformation numérique', 'Début d’une refonte numérique et intelligente systématique du système de production.'],
        ['2023', 'Parc de Deqing en production', 'Ateliers numériques et entrepôt automatisé sur un parc intelligent de 120 000 m².'],
        ['2025', 'Fabrication dopée à l’IA', 'Intégration profonde IA-fabrication, cas modèle provincial et national.'],
      ],
    },
    about: {
      title: 'À propos',
      heroTitle: 'D’une station de pompage de quatre personnes au STAR Market.',
      heroBody: 'Xili descend de la Hangzhou Watt-Hour Meter Factory, fondée en 1968. En 1999, elle est restructurée en Hangzhou Xili Electric Energy Meter Manufacturing Co., Ltd. ; en 2016, elle devient société par actions ; et le 18 mars 2021, elle est cotée au STAR Market de la Bourse de Shanghai — la première société de compteurs intelligents à l’être.',
      storyTitle: 'Près de six décennies, une conviction',
      storyBody: '« La qualité comme fondement, la technologie comme victoire » guide Xili depuis près de soixante ans — du compteur mécanique au compteur intelligent, de la fabrication traditionnelle à la production dopée à l’IA. Privatisée en 1999, au-delà des cent millions de yuans de revenus en 2010, cotée au STAR Market en 2021, et aujourd’hui dotée d’une usine intelligente de niveau provincial dans le parc scientifique de Deqing. Outre les compteurs, terminaux d’acquisition et coffrets de comptage, l’entreprise applique la même discipline « comptage plus communications » à la mesure de recharge des VE et vélos électriques, à la supervision énergétique des stations 5G et aux compteurs d’eau intelligents. Xili exploite 34 lignes automatisées et plus de 270 équipements intelligents de haut niveau, pour une capacité annuelle supérieure à dix millions de compteurs et terminaux, au service de plus de 500 clients dans 33 régions provinciales — avec des produits conformes aux contrôles qualité nationaux et provinciaux depuis vingt années consécutives.',
      globalIndex: 'Empreinte mondiale',
      globalTitle: 'Mesuré chez nous. Reconnu ailleurs.',
      globalBody: 'Xili sert plus de 500 clients dans les 33 régions provinciales de Chine et exporte ses produits de comptage vers l’Asie du Sud-Est, l’Afrique, l’Europe de l’Est et l’Amérique du Sud. L’entreprise est membre de la DLMS User Association (Suisse) et de la STS Association (Afrique du Sud) — les deux organismes qui régissent la communication et le prépaiement des compteurs dans le monde.',
      globalHub: 'Hangzhou',
      globalMarkets: ['Thaïlande', 'Bangladesh', 'Corée du Sud', 'Philippines', 'Europe de l’Est', 'Ghana', 'Chili', 'Équateur', 'Pakistan'],
      globalStats: [
        [33, '', 'Régions provinciales en Chine'],
        [10, '', 'Marchés export'],
        [24, '', 'Partenaires de long terme'],
      ],
      investorIndex: 'Relations investisseurs',
      investorTitle: 'Cotée. Auditée. Distributrice de dividendes.',
      investorStats: [
        ['566 M¥', 'Chiffre d’affaires · 2025'],
        ['104 M¥', 'Résultat net · 2025'],
        ['5,5 %', 'Du chiffre d’affaires en R&D'],
        ['50,9 %', 'Taux de distribution du dividende'],
      ],
      investorNote: 'Hangzhou Xili Intelligent Technology Co., Ltd. — 688616.SH, STAR Market, Bourse de Shanghai. Comptes audités par Pan-China CPAs, opinion sans réserve. Relations investisseurs : zqb@cnxili.com',
      subsidiariesIndex: 'Structure du groupe',
      subsidiariesTitle: 'Deux filiales à 100 %.',
      subsidiaries: [
        ['Zhejiang Xili Intelligent Technology', 'Équipements de distribution intelligents', 'Fournisseur clé de coffrets de comptage intelligents, d’armoires BT intégrées, de coffrets de dérivation de câbles et de disjoncteurs sur poteau à intégration primaire-secondaire. Dispose de ses propres presses à injecter, centres d’usinage CNC, machines à électroérosion et lignes d’assemblage automatisées, d’un centre de R&D municipal et d’un institut de recherche provincial, sous ISO 9001, 14001, 45001 et 50001. Usine intelligente du Zhejiang en 2023.'],
        ['Zhejiang Xili New Energy', 'Stockage d’énergie distribué', 'Dotée d’un capital de 50 millions de yuans, elle se consacre au stockage distribué et aux microréseaux. Elle développe et fabrique des stations portables, des systèmes solaires domestiques hors réseau et du stockage résidentiel et commercial, en s’appuyant sur le centre technologique provincial et le laboratoire CNAS du groupe. ISO 9001, 14001 et 45001. Promesse de marque : « Énergie Xili — verte et sûre ».'],
      ],
      valuesTitle: 'Culture d’entreprise',
      valuesLede: 'Depuis sa création, Xili s’en tient à une philosophie de développement — « la qualité comme fondement, la technologie comme victoire » — et à une philosophie de gestion — « engagement, discipline, rigueur, précision » — appliquées sous une seule exigence : l’exécution avant tout, les détails décident du résultat. Innovation technologique et probité guident la stratégie, les règles et le développement des personnes.',
      values: [
        ['Mission', 'Faire progresser le comptage de l’énergie ; servir chaque utilisateur.'],
        ['Vision', 'Devenir le leader de l’industrie chinoise des instruments électriques — et une entreprise respectée.'],
        ['Valeurs fondamentales', 'Le client d’abord. L’excellence dans la gestion.'],
        ['Principe directeur', 'Innovation technologique et probité.'],
        ['Philosophie de gestion', 'Engagement, discipline, rigueur, précision.'],
        ['Philosophie de développement', 'La qualité comme fondement ; la technologie comme victoire.'],
      ],
      timelineTitle: 'Jalons',
      timeline: [
        ['1968', 'Fondation', 'Débuts comme station de pompage de 3–4 personnes de l’usine de machines agricoles du Lac de l’Ouest.'],
        ['1999', 'Privatisation', 'Réforme actionnariale ; l’entreprise devient Hangzhou Xili Electric Energy Meter Manufacturing.'],
        ['2010', '100 M¥ de revenus', 'Le chiffre d’affaires dépasse cent millions de yuans après de solides appels d’offres State Grid.'],
        ['2016', 'Société par actions', 'Renommée Hangzhou Xili Intelligent Technology Co., Ltd. ; gouvernance moderne en place.'],
        ['2021', 'Cotation au STAR Market', 'Cotée le 18 mars 2021 (688616) — première société de compteurs intelligents cotée au STAR Market.'],
        ['2023', 'Parc de Deqing', 'Le parc industriel intelligent de 120 000 m² entre en pleine production : ateliers numériques, entrepôt automatisé.'],
        ['2024', 'Résultats records', 'Bénéfice net record de 104 millions de yuans ; plateforme d’exploitation numérique en service.'],
        ['2025', 'L’IA dans l’usine', 'L’intégration IA-fabrication devient cas modèle provincial et national ; revenus nouvelles énergies en hausse de 281 %.'],
      ],
      honorsTitle: 'Distinctions et qualifications',
      honorStats: [
        [132, '', 'Brevets délivrés'],
        [148, '', 'Droits d’auteur logiciels'],
        [42, '', 'Normes corédigées'],
        [40, '+', 'Résultats scientifiques certifiés'],
      ],
      honors: [
        'Fournisseur State Grid : classe A à chaque évaluation depuis 2019',
        'Marque notoire de Chine',
        'Entreprise nationale de haute technologie',
        'Usine verte nationale (MIIT, 2025)',
        'Unité nationale de création en propriété intellectuelle',
        'Centre d’essais accrédité CNAS (CNAS L9323)',
        'Entreprise « champion caché » provinciale (2025)',
        'Institut de recherche d’entreprise clé provincial (2025)',
        'Plateforme provinciale clé de l’internet industriel (2026)',
        'PME « spécialisée et innovante » du Zhejiang',
        'Certification « Zhejiang Manufacturing » · certification produit économe en énergie',
        'Système de management de la mesure ISO 10012',
        'Système de management de la sécurité de l’information ISO 27001',
        'Systèmes de management ISO 9001 · 14001 · 45001 · 50001',
        'Systèmes de management de la PI et de la responsabilité sociétale',
        'Certificats d’empreinte carbone produit pour les transformateurs de mesure',
        'Système de management de l’écoconception, niveau AAAAA',
        'Systèmes de management de la chaîne verte et des gaz à effet de serre',
        'Prix du progrès scientifique et technologique du Zhejiang',
        'Prix national de l’invention et de l’entrepreneuriat',
        'Prix chinois de l’excellence en brevets (2018)',
        'Membre de la DLMS User Association et de la STS Association',
        'Première société de compteurs intelligents cotée au STAR Market',
      ],
      csrTitle: 'Responsabilité',
      csr: [
        ['Fabrication verte et bas carbone', 'Modernisation verte des procédés depuis 2014, primée au niveau provincial ; vérification carbone et certification d’empreinte en soutien des objectifs bas-carbone.'],
        ['Gouvernance responsable', 'Systèmes de management qualité, environnement, santé-sécurité et sécurité de l’information — avec un rapport ESG annuel.'],
        ['Solidarité et attention', 'Un fonds caritatif dédié a soutenu 55 patients avec 225 400 ¥ d’aides à fin 2025, aux côtés de dons anti-pandémie et de collectes de sang du personnel.'],
      ],
      officialAction: 'Site officiel Xili Technology',
      officialUrl: 'https://www.cnxili.com/en/WestForceProfile/index.aspx',
    },
    news: {
      title: 'Actualités',
      heroTitle: 'Actualités et jalons.',
      heroBody: 'Les annonces de l’entreprise et les jalons qui ont façonné Xili — mis à jour au fil de l’histoire.',
      items: [
        ['2026', 'Contrats', 'Plus de 162 millions de yuans remportés auprès de State Grid', 'Xili est retenue au premier appel d’offres 2026 de State Grid en équipements de comptage — compteurs monophasés classe A, triphasés classes B/C, terminaux de fusion intelligents et transformateurs de mesure — pour 162 millions de yuans au total, avec d’autres succès au Hubei, en Anhui, au Heilongjiang et à Shanghai.', 'meter-line'],
        ['2026', 'ESG', 'Publication des rapports ESG 2025', 'Hangzhou Xili et Zhejiang Xili publient leurs rapports environnementaux, sociaux et de gouvernance 2025, étendant la transparence aux activités comptage et énergies nouvelles.', 'pv-solution'],
        ['2026', 'Résultats', 'Exercice 2025 : profit stable et 52,9 M¥ de dividendes', 'Chiffre d’affaires de 566 millions de yuans, résultat net de 104 millions, flux de trésorerie d’exploitation en hausse de 53 %. Un dividende de 3 ¥ par 10 actions reverse 50,9 % du résultat net aux actionnaires.', 'zhuantang-hq'],
        ['2026', 'Fabrication', 'L’usine du futur retenue comme projet de démonstration du Zhejiang', 'La modernisation « usine du futur » des terminaux de comptage intelligents est retenue sur la liste 2026 des projets de démonstration de transformation productive de la province du Zhejiang.', 'robot-cell'],
        ['2026', 'Distinction', 'Usine verte et bas carbone de niveau national', 'Xili Technology reçoit la distinction nationale « usine verte et bas carbone », saluant une fabrication sobre en énergie et en émissions.', 'deqing-park'],
        ['2025', 'Jalon', 'L’intégration IA-fabrication devient cas modèle national', 'L’intégration profonde de l’IA dans la fabrication de Xili est retenue comme cas modèle provincial et national ; les revenus de Xili New Energy progressent de 281 % sur un an.', 'robot-glow'],
        ['2024', 'Résultats', 'Bénéfice net record de 104 millions de yuans', 'Le bénéfice net annuel atteint un record de 104 millions de yuans ; la plateforme d’exploitation numérique entre en service.', 'hall'],
        ['2023', 'Fabrication', 'Le parc industriel de Deqing en pleine production', 'Le parc intelligent de 120 000 m² entre en pleine production : ateliers numériques et entrepôt automatisé en service.', 'campus-aerial'],
        ['2021', 'Jalon', 'Xili Technology entre au STAR Market', 'Hangzhou Xili Intelligent Technology (688616.SH) est cotée au STAR Market de la Bourse de Shanghai — un engagement public envers l’ingénierie de précision.', 'listing-2021'],
        ['2005', 'Fabrication', 'Le cap de l’usine numérique', 'Xili relie cycle de vie produit, exécution de fabrication et données machines en une seule boucle — une qualité mesurée, jamais supposée.', 'factory-2005'],
        ['1968', 'Héritage', 'Naissance de l’héritage du comptage', 'Le socle industriel du comptage électrique qui ancre encore la culture de précision de Xili.', 'heritage-1968'],
      ],
      note: 'Les annonces suivantes sont publiées après vérification officielle.',
    },
    careers: {
      title: 'Carrières',
      heroTitle: 'Construisez les instruments du réseau.',
      heroBody: 'Le travail de précision demande des gens précis. Rejoignez une équipe où la mesure est un art et l’énergie une mission.',
      whyTitle: 'Pourquoi Xili',
      why: [
        ['De vraies infrastructures', 'Votre travail part dans les réseaux, les usines et les foyers — sur des décennies.'],
        ['Une profondeur d’ingénierie', 'Métrologie, électronique de puissance, communications et systèmes industriels sous un même toit.'],
        ['Une plateforme cotée', 'La stabilité d’une société cotée au STAR Market, la concentration d’un spécialiste.'],
      ],
      areasTitle: 'Directions de recrutement',
      areas: [
        ['Ingénierie R&D', 'Comptage, stockage, embarqué et communications.'],
        ['Fabrication & supply chain', 'Usine numérique, procédés et équipements.'],
        ['Qualité & essais', 'Vérification métrologique, de la ligne au laboratoire.'],
        ['Marchés & ventes', 'Programmes réseau et développement international.'],
      ],
      action: 'Présentez-vous',
      note: 'Envoyez votre CV et la direction qui vous intéresse — nous répondons à toute candidature sérieuse.',
    },
    contact: {
      title: 'Contact',
      heroTitle: 'Rendons l’énergie plus lisible.',
      heroBody: 'Indiquez-nous où votre système énergétique a besoin de plus de précision, de visibilité ou de résilience.',
      action: 'Démarrer une conversation',
      channelsTitle: 'Nous joindre',
      email: 'hzxilidb@cnxili.com',
      offices: 'Hangzhou · Deqing · Chine',
      officeTitle: 'Implantations',
      locations: [
        ['zhuantang-hq', 'Siège · Hangzhou', 'No 173 route Liangfu, Zhuantang, district de Xihu, Hangzhou 310024, Zhejiang, Chine · +86 571 87825461 / 56660360'],
        ['deqing-park', 'Site de production · Deqing', 'No 733 route Huancheng Nord, comté de Deqing, Huzhou 313000, Zhejiang, Chine · +86 572 8233298 / 8233258'],
      ],
      emailTitle: 'E-mail',
      responseNote: 'Nous répondons aux demandes de solution sous deux jours ouvrés.',
    },
    footer: {
      descriptor: 'Intelligence énergétique',
      colProducts: 'Produits',
      colSolutions: 'Solutions',
      colCompany: 'Entreprise',
      legal: '© 2026 Xili Technology. Tous droits réservés.',
    },
  },

  zh: {
    locale: '中',
    code: 'zh',
    meta: {
      title: '西力科技 — 智慧能源',
      description: '以精准为基础的智慧能源体系，从电力计量到可靠储能。',
    },
    common: {
      home: '首页',
      explore: '了解详情',
      learnMore: '了解更多',
      viewAll: '查看全部',
      backTo: '返回',
      discuss: '洽谈解决方案',
      contactUs: '联系我们',
      menu: '菜单',
      close: '关闭菜单',
      related: '相关推荐',
      keyPoints: '核心能力',
      process: '交付流程',
      categories: '产品线',
      directions: '方案方向',
      scroll: '向下浏览',
      breadcrumbProducts: '产品体系',
      breadcrumbSolutions: '解决方案',
      imageSoon: '图片即将上线',
      readMore: '阅读更多',
    },
    nav: {
      products: '产品体系',
      solutions: '解决方案',
      technology: '技术实力',
      about: '关于西力',
      news: '新闻动态',
      careers: '加入我们',
      contact: '联系我们',
    },
    marquee: ['智能计量', '用电采集', '智能配网', '储能系统', '数字化管理', '精准工程'],
    home: {
      heroKicker: '精密计量赋能电力物联的科创领航者',
      heroTitle: '智能电表 · 智能配网 · 储能系统。',
      heroBody: '杭州西力做电力级的电能计量、智能配网设备与储能系统——从电网末端的每一块表，到工商业侧的储能。2021 年登陆科创板。',
      heroPrimary: '了解产品体系',
      heroSecondary: '认识西力',
      stats: [
        [1968, '', '创业起点'],
        [2021, '', '科创板上市'],
        [500, '+', '服务客户'],
        [33, '', '覆盖省级区域'],
      ],
      pillarsIndex: '总览',
      pillarsTitle: '一层智能底座，三大核心能力。',
      pillarsBody: '西力把电能计量、智能配网与储能系统收敛为一条产品主线。',
      pillars: [
        ['01', '智能计量', '从居民表到关口表，把每一度电测准。'],
        ['02', '智能配网', '计量箱、低压配电箱柜与柱上断路器，护住计量点。'],
        ['03', '储能系统', '从便携电源到工商业储能的分布式方案。'],
      ],
      productsIndex: '产品体系',
      productsTitle: '围绕能源链构建的产品体系。',
      productsBody: '计量、配网、储能三条产品线，每条都有独立的详细介绍。',
      solutionsIndex: '解决方案',
      solutionsTitle: '让能源加速向前的系统。',
      solutionsBody: '五个解决方案方向——电网、综合能源、工商业、公寓与校园，由同一套精准的能源语言贯通。',
      technologyIndex: '技术实力',
      technologyTitle: '精准，是一套运行系统。',
      technologyBody: '前面是百人研发团队与省级重点企业研究院，后面是 34 条自动化产线，同一套数字化管理平台把研发到交付串成一条线。',
      technologyAction: '看研发与制造',
      newsIndex: '新闻动态',
      newsTitle: '来自西力的最新动态。',
      partnersIndex: '合作伙伴',
      partnersTitle: '与能源链上的同行者并肩。',
      partnersBody: '与西力同行的电网企业、新能源领军企业，以及上下游供应链伙伴。',
      zhFirst: true,
      ctaTitle: '让能源更加清晰可读。',
      ctaBody: '告诉我们您的能源系统在哪些方面需要更高的精准度、可视化与可靠性。',
    },
    products: {
      title: '产品体系',
      catalogIndex: '产品目录',
      heroTitle: '四大产品系列，同一套计量纪律。',
      heroBody: '此处每一款产品均出自西力官方产品折页——准确度等级、额定参数与通信协议均按折页所载呈现。',
      seriesNote: '型号、准确度等级与额定参数均以西力官方产品折页所载为准。',
      categories: [
        {
          slug: 'metering-instruments',
          name: '计量仪表',
          tagline: '让电网放心的精准计量。',
          description: '面向国家电网与南方电网标准的交直流智能电能表、采集终端与双模通信模块。',
          longText: '这是西力的主业，也是自 2019 年国网供应商绩效评价以来历次获评最高等级 A 类的原因。交直流电能表、采集终端与承载数据的 HPLC+HRF 双模模块被作为一个系统来设计——精准计量、远程费控、事件记录与加密传输，从单个住户到整个台区。',
          items: [
            ['智能电能表', '覆盖国网与南网两大标准体系的 A/B/C 级单相与三相交流表，以及 0.5 级与 1 级、最高 1000V/600A 的直流表，适用于充电桩、光伏与铁塔通信。'],
            ['智能水表', '支持 NB-IoT 与 LoRa 的远传、阀控与超声波水表，可与电表同平台抄收。'],
            ['终端与模块', '能源控制器、智能融合终端、集中器与 HPLC+HRF 双模通信模块。'],
          ],
          points: ['2019 年以来国网供应商历次评价 A 类', 'DL/T 698.45 与 DL/T 645 协议体系', 'HPLC+HRF 双模通信'],
        },
        {
          slug: 'metering-transformers',
          name: '计量互感器',
          tagline: '计量链路的第一环。',
          description: '0.66kV 至 35kV 的电流、电压与组合互感器，准确度等级 0.2S、0.5S。',
          longText: '电表再准，也准不过给它供电的互感器。西力的电流、电压与组合互感器均为自主研发生产，并在公司自有的 CNAS 认可实验室（CNAS L9323）完成检定。互感器与电表按同一套标准验证，所以准确度等级覆盖的是整条计量链路，而不是链路上的某一件设备。',
          items: [
            ['低压电流互感器', '0.66kV、0.2S/0.5S 级，变比覆盖 75/5A 至 3000/5A。'],
            ['中压电流与电压互感器', '面向 10–35kV 系统的环氧树脂干式产品，防污设计。'],
            ['组合互感器', 'PT 与 CT 一体化，用于高压线路直接计量。'],
          ],
          points: ['0.2S 与 0.5S 准确度等级', '自主研发生产', '互感器检定在自有 CNAS 认可实验室（L9323）'],
        },
        {
          slug: 'distribution-network',
          name: '配电网产品',
          tagline: '守护计量点的配网装备。',
          description: '浙江西力智能科技的电能计量箱、智能低压综合配电箱与柱上断路器。',
          longText: '全资子公司浙江西力智能科技，制造承载与保护计量点的硬件：PC+ABS、SMC 与不锈钢材质的电能计量箱、一体化低压配电箱，以及一二次融合柱上断路器。自建模具中心、注塑机与数控加工中心，把工装与一致性掌握在自己手里。',
          items: [
            ['电能计量箱', '依据 Q/GDW 11008-2013 的单相与三相计量箱，复合材料或不锈钢箱体。'],
            ['配电箱柜', '挂墙式配电箱与配变旁的一体化智能低压配电箱。'],
            ['柱上开关设备', 'ZW32 一二次融合柱上断路器，集测量、保护与遥测遥控于一体。'],
          ],
          points: ['Q/GDW 11008-2013 计量箱', '自建模具中心与注塑产线', 'ISO 9001 · 14001 · 45001 · 50001'],
        },
        {
          slug: 'new-energy',
          name: '储能产品',
          tagline: '把电留到最需要的时刻。',
          description: '浙江西力新能源的便携储能电源与离网太阳能家用系统，底层是分布式储能与微电网技术。',
          longText: '注册资金 5000 万元的浙江西力新能源，做的是分布式储能与微电网技术：从户外作业和家庭备电的便携电源，到家庭储能与工商业储能。依托母公司省级企业技术中心与 CNAS 实验室，按 ISO 9001、14001、45001 体系生产。',
          items: [
            ['便携储能电源', '288Wh 至 1076Wh，交流、直流、USB 输出，支持太阳能充电。'],
            ['离网太阳能系统', '50Wp 太阳能家用系统，支持 PAYGO 计量，用于离网照明与充电。'],
            ['家庭与工商业储能', '面向削峰填谷、备用电源与自发自用的分布式储能。'],
          ],
          points: ['分布式储能与微电网技术', '依托集团 CNAS 实验室', 'ISO 9001 · 14001 · 45001'],
        },
      ],
    },
    solutions: {
      title: '解决方案',
      heroTitle: '让能源加速向前的系统。',
      heroBody: '五个解决方案方向——电网、综合能源、工商业、公寓与校园，由同一套精准的能源语言贯通。',
      items: [
        {
          slug: 'grid-intelligence',
          name: '电网智能',
          tagline: '更清晰可见的电网边缘。',
          description: '面向电力公司与电网运营方的智能计量、用电采集与电能计量系统。',
          longText: '电网智能始于计量点。西力将智能电表、采集终端与计量箱系统组合为成套部署方案，让运营方对电网边缘拥有精准、连续的可视化。',
          points: [
            ['精准计量', '按电力项目精度等级要求打造的计量产品。'],
            ['互联采集', '将用电数据可靠传入电力系统的终端与集中器。'],
            ['部署经验', '以数十年计的计量积淀，应用于现代化改造项目。'],
          ],
          steps: ['评估计量现状', '配置产品与通信', '规模化部署与校验', '存量设备持续服务'],
        },
        {
          slug: 'pv-storage-charging',
          name: '光伏 · 储能 · 充电',
          tagline: '一体化的能源闭环。',
          description: '面向光伏发电、储能与充电的一体化解决方案方向。',
          longText: '发电、储能与充电是一个系统，而非三个。该方向将光伏输入、储能与充电负载纳入统一的计量与控制之下——让能源在最需要、最有价值的时刻流向该去的地方。',
          points: [
            ['面向发电的储能', '按真实光伏出力曲线配置与控制储能。'],
            ['充电一体化', '充电负载作为能源闭环的一部分统一管理。'],
            ['全程可计量', '西力的计量纪律贯穿系统中每一路能量流。'],
          ],
          steps: ['分析发电与负载曲线', '设计一体化系统', '安装与调试', '全程可视化运行'],
        },
        {
          slug: 'commercial-energy',
          name: '工商业能源管理',
          tagline: '让能源成为经营优势。',
          description: '面向工业与商业需求的综合能源管理解决方案方向。',
          longText: '对工商业场所而言，能源是可管理的成本，也是韧性问题。该方向将计量、储能与管理相结合，让运营者清晰看见能耗，并有信心地采取行动。方案已应用于科技园区、商业楼宇、企业单位与综合体商场：门禁、电、水数据在同一管理端抄收、统计与控制，微信与 APP 客户端支持查询、充值与故障报修，云服务平台支持多方互联。',
          points: [
            ['可视化优先', '覆盖回路、负载与时段的精细计量。'],
            ['储能用在刀刃上', '将工商业储能应用于削峰、备电与自发自用。'],
            ['一个管理闭环', '数据、储能与控制协同为一个系统。'],
          ],
          steps: ['能源流审计', '价值模型测算', '部署计量与储能', '持续管理与优化'],
        },
        {
          slug: 'apartment-energy',
          name: '公寓能源管理',
          tagline: '租住运营，一个平台跑通。',
          description: '面向集中式、分散式与共享公寓的智能软硬件管理系统——合同、租金与水电气在同一平台管理。',
          longText: '智慧公寓方案为运营商提供覆盖租住业务全流程的管理端：合同、租金与代理物业服务，连同门锁、电、水、气等智能设备的数据抄收统计、远程控制与信息发布。租户通过 APP 或微信客户端查询并充值房租与水电气费、远程开锁、控制智能硬件、一键报修。云服务平台支持多方互联，服务智慧公寓生态伙伴。',
          points: [
            ['一个运营管理端', '合同、租金、物业服务与智能设备数据——同一平台抄收、统计与控制。'],
            ['有回应的租户端', '房租水电气查询与充值、远程门锁、智能硬件控制、一键故障报修。'],
            ['开放的云平台', '面向公寓生态的多方互联——运营商、业主与服务伙伴互利共赢。'],
          ],
          steps: ['梳理租住房源现状', '部署智能门锁、表计与传感', '接入管理端与租户端', '运营结算，持续增长'],
        },
        {
          slug: 'campus-energy',
          name: '校园能源管理',
          tagline: '让校园水电清晰可控。',
          description: '面向学校与校园的水电一体化智能管理方案——智能硬件、物联网通信、云平台与移动端合为一个系统。',
          longText: '方案基于西力自研的智能电表、智能水表与集中器，为校园管理者提供水电合一的管理平台：远程抄表与远程阀控/跳合闸，预付费与自动催缴，并可针对宿舍与教学楼设置定时供电、恶性负载识别与过载保护等安全策略。',
          points: [
            ['远程抄表与控制', '水电数据同平台远程采集，支持按房间、按楼栋远程控制开关与阀门。'],
            ['预付费与自动催缴', '预付费账户、余额不足自动提醒，每间宿舍费用清晰可结。'],
            ['以策略保安全', '定时供电时段、过载与恶性负载保护，为学生住宿场景专门设计。'],
          ],
          steps: ['调研校园水电现状', '部署智能表计与集中器', '接入云平台与移动端', '运营、计费与持续优化'],
        },
      ],
    },
    technology: {
      title: '技术实力',
      heroTitle: '精准，是一套运行系统。',
      heroBody: '研发与生产是一套系统。研发端：省级重点企业研究院、省级企业技术中心与超过百人的研发团队；生产端：位于德清的省级智能工厂，34 条自动化生产线、270 余台高端智能装备及全自动仓储物流系统，年产能超千万只智能电表及终端产品。',
      sectionTitle: '研发与数字化管理',
      sectionBody: '研发能力与制造能力放在同一个平台上管。自 2005 年起投入信息化管理体系建设，自 2012 年起系统推进数字化、智能化转型——质量靠测量验证，而非假设。',
      list: [
        ['多层级研发与测试平台', '拥有省级重点企业研究院、高新技术企业研究开发中心、省级企业技术中心，以及通过 CNAS 国家实验室认可的测试中心，研发团队超过百人。'],
        ['八大核心技术体系', '涵盖高可靠性数据存储数据库中间件技术、软件功能模块化设计技术、高精度计量技术等，构筑坚实技术壁垒。'],
        ['产学研协同', '多次参与国家标准与行业标准的制定，部分科研项目被列入国家火炬计划产业化示范项目；与香港大学、杭州电子科技大学、浙江科技学院等高校建立紧密合作关系。'],
        ['数字化管理平台', '自 2005 年起投入信息化管理体系建设，集成 ERP、MES、PLM、EMS、EHR 及国网 NQI 厂家侧数据采集系统，实现从研发到生产到交付的全过程数字化管理。'],
      ],
      note: '为现代能源基础设施的可靠部署而构建。',
      twinIndex: '数字孪生',
      twinTitle: '一座在数据中运行的工厂。',
      twinBody: '产线、立库与检测台架汇入同一个实时数字模型——驱动 MES 排产的遥测数据，同时把车间渲染为一座“活的孪生工厂”：每台设备都可观测、可仿真、可优化。',
      twinTags: ['SMT 与组装产线', '自动化检定', '智能立体仓库', 'AGV 物流'],
      aiIndex: 'AI 与智能化',
      aiTitle: 'AI 与我们并肩上产线。',
      aiBody: '西力 AI 与制造深度融合入选省级、国家级典型案例。在这里，智能化不是试点项目——它嵌入在检测、排产与日常运营之中。',
      aiList: [
        ['大模型应用', 'AI 大模型嵌入质量分析、生产知识与运营流程——答案来自工厂自己的数据。'],
        ['机器视觉检测', '视觉系统在线检测电路板与组件，以产线速度拦截缺陷，不让问题流向下游。'],
        ['AI 辅助排产', '算法在 34 条产线、270 余台设备间统筹规划，在 MES 中平衡交付节点与产能。'],
        ['数字化运营平台', '公司级运营的可视化、数据化管理——2024 年上线，贯通订单到交付。'],
      ],
      labsIndex: '实验室',
      labsTitle: '全天候运转的自动化实验室。',
      labsBody: '西力测试中心已通过中国合格评定国家认可委员会认可（CNAS L9323），电表、互感器与终端产品在这里完成检定、老化与认证，自动化台架不随班次停。连续二十年通过国家级与省级质量监督抽查，靠的就是这一套自己说了算的验证能力。',
      labsList: [
        ['自动化检定与校准', '自动化台架对照基准标准批量检定电表与互感器——高通量、少人工、可审计。'],
        ['可靠性与环境试验', '高低温、湿热、浪涌与寿命试验箱，把多年现场应力浓缩进实验室。'],
        ['EMC 与电气安全', '电磁兼容与安全测试台架，为电网环境与出口市场做产品资质验证。'],
        ['储能测试', '电芯与 PACK 台架在全温度窗口内对储能产品做充放循环与滥用测试。'],
      ],
      ipIndex: '标准与知识产权',
      ipTitle: '把名字写进标准里。',
      ipStats: [
        [132, '', '授权专利'],
        [27, '', '发明专利'],
        [148, '', '软件著作权'],
        [42, '', '参与制定国家、行业及团体标准'],
      ],
      ipNote: '荣誉包括：中国专利优秀奖（2018）、中国发明协会发明创业奖·成果奖二等奖（2025），DJTD23-XL31102 型集中器入选 2025 年“浙江制造精品”。',
      milestonesTitle: '工程里程碑',
      milestones: [
        ['2005', '信息化建设起步', '启动信息化管理体系建设，逐步集成 ERP、MES、PLM 等系统。'],
        ['2012', '数字化转型', '系统推进生产制造体系的数字化、智能化转型。'],
        ['2023', '德清产业园投产', '12 万平方米智能化产业园：数字化车间、智能立库投用。'],
        ['2025', 'AI 赋能制造', 'AI 与制造深度融合，入选省级、国家级典型案例。'],
      ],
    },
    about: {
      title: '关于西力',
      heroTitle: '从三四人的排灌站，到科创板上市。',
      heroBody: '公司前身为始创于 1968 年的杭州电度表厂。1999 年，杭州电度表厂与杭州市西湖仪表工业公司经批准改制设立杭州西力电能表制造有限公司；2016 年整体变更为杭州西力智能科技股份有限公司；2021 年 3 月 18 日成功登陆上交所科创板，成为智能电表行业首家科创板上市企业。',
      storyTitle: '五十余载，一个信念',
      storyBody: '公司专业从事智能电表、用电信息采集终端、电能计量箱等电能计量产品的研发、生产和销售，并将计量技术与通讯技术相融合，进行新能源汽车和电动自行车充电计量、5G 基站能效监控、智能水表等产品和市场的开发，是国家级高新技术企业。历经五十余载技术积淀与创新突破，西力科技已从传统的电表制造商，成长为以科技创新为核心驱动、深度参与电力物联网建设的行业标杆。今天的西力在德清科技园建成省级智能工厂，配置 34 条自动化生产线、270 余台高端智能装备及全自动仓储物流系统，具备年产超千万只智能电表及终端产品的能力；服务客户 500 余家、覆盖全国 33 个省级区域，产品远销东南亚、非洲、东欧与南美市场，并连续二十年通过国家级与省级质量监督抽查。',
      globalIndex: '全球布局',
      globalTitle: '深耕国内，走向海外。',
      globalBody: '西力服务客户 500 余家，覆盖全国 33 个省级区域；计量产品远销东南亚、非洲、东欧与南美市场。公司是瑞士 DLMS 技术协会与南非 STS 技术协会会员——这两个国际组织定义着全球电表的通信与预付费标准。',
      globalHub: '杭州',
      globalMarkets: ['泰国', '孟加拉', '韩国', '菲律宾', '东欧', '加纳', '智利', '厄瓜多尔', '巴基斯坦'],
      globalStats: [
        [33, '', '覆盖省级区域'],
        [10, '', '海外出口市场'],
        [24, '', '长期合作伙伴'],
      ],
      investorIndex: '投资者关系',
      investorTitle: '上市公司的透明度。',
      investorStats: [
        ['5.66 亿元', '2025 年营业收入'],
        ['1.04 亿元', '2025 年归母净利润'],
        ['5.5%', '研发投入占营收比'],
        ['50.9%', '现金分红占净利润比'],
      ],
      investorNote: '杭州西力智能科技股份有限公司——688616.SH，上海证券交易所科创板。天健会计师事务所出具标准无保留意见审计报告。投资者关系：zqb@cnxili.com',
      subsidiariesIndex: '集团架构',
      subsidiariesTitle: '两家全资子公司。',
      subsidiaries: [
        ['浙江西力智能科技有限公司', '智能配网设备', '智能配网设备领域的重要供应商，专注智能计量箱、智能低压综合配电箱、电缆分支箱、一二次融合柱上断路器的研发、生产与销售。拥有注塑机、数控加工中心、电火花成型机及多条自动化产线，建成市级科技企业研发中心及省级企业研究院，全面实施 ISO9001、ISO14001、ISO45001 及 ISO50001 管理体系，2023 年获评浙江省智能工厂。'],
        ['浙江西力新能源有限公司', '分布式储能', '注册资金 5000 万元人民币，专注分布式储能技术和微电网技术的研究及创新。依托母公司省级企业技术中心和 CNAS 实验室，致力于便携储能、离网太阳能系统、家庭储能与工商业储能等产品研发。已通过 ISO9001、ISO14001、ISO45001 体系认证，品牌愿景“西力电源，绿色安全”。'],
      ],
      valuesTitle: '企业文化',
      valuesLede: '公司自创立以来，一直秉承“质量为本，科技致胜”的发展理念和“敬业、服从、规范、精细”的管理理念，贯彻“执行力高于一切，细节决定成败”的管理要求，以科技创新、诚实守信的经营风范，规划实施企业发展战略，健全规范各项规章制度，实施企业文化建设方案，加强人才培养与充实，不断提升企业综合实力。',
      values: [
        ['企业使命', '发展能源计量，服务广大用户。'],
        ['企业愿景', '成为中国电工仪表行业的领跑者和受人尊敬的企业！'],
        ['企业价值观', '客户第一、卓越管理。'],
        ['发展理念', '质量为本，科技致胜。'],
        ['管理理念', '敬业、服从、规范、精细。'],
        ['管理要求', '执行力高于一切，细节决定成败。'],
      ],
      timelineTitle: '发展里程碑',
      timeline: [
        ['1968', '创业起点', '从西湖农机厂三四人的排灌站起步。'],
        ['1999', '改制民营', '完成股份制改造，更名"杭州西力电能表制造有限公司"，从集体所有制转型民营。'],
        ['2010', '营收破亿', '国网集中招标中崭露头角，销售收入首次突破亿元大关。'],
        ['2016', '股份制改造', '更名"杭州西力智能科技股份有限公司"，建立现代企业治理结构。'],
        ['2021', '科创板上市', '3 月 18 日正式上市（股票代码 688616），成为智能电表行业首家科创板上市企业。'],
        ['2023', '德清产业园投产', '12 万平方米智能化产业园全面投产，数字化车间、智能立库投用。'],
        ['2024', '业绩创新高', '全年净利润达 1.04 亿元创历史新高；数字化运营平台上线。'],
        ['2025', 'AI 深度融合', 'AI 与制造深度融合入选省级、国家级典型案例；新能源销售收入同比增长 281%。'],
      ],
      honorsTitle: '荣誉资质',
      honorStats: [
        [132, '', '授权专利'],
        [148, '', '软件著作权'],
        [42, '', '参与制定标准'],
        [40, '+', '科技成果鉴定证书'],
      ],
      honors: [
        '国网供应商绩效评价：2019 年以来历次最高等级 A 类',
        '中国驰名商标',
        '国家级高新技术企业',
        '国家级绿色工厂（工业和信息化部，2025 年度）',
        '国家知识产权创建单位',
        'CNAS 认可测试中心（CNAS L9323）',
        '省级隐形冠军企业（2025）',
        '省重点企业研究院（2025 年度）',
        '省级重点工业互联网平台（2026 年度）',
        '浙江省专精特新中小企业',
        '浙江制造认证 · 中国节能产品认证',
        'ISO 10012 测量管理体系认证',
        'ISO 27001 信息安全管理体系认证',
        'ISO 9001 · 14001 · 45001 · 50001 管理体系认证',
        '知识产权管理体系认证 · 社会责任管理体系认证',
        '互感器产品碳足迹认证证书',
        '绿色设计产品管理体系认证 AAAAA',
        '绿色供应链与温室气体排放管理体系认证',
        '浙江省科学技术进步奖',
        '国家发明创业奖',
        '中国专利优秀奖（2018）',
        '瑞士 DLMS 技术协会会员 · 南非 STS 技术协会会员',
        '智能电表行业首家科创板上市企业',
      ],
      csrTitle: '社会责任',
      csr: [
        ['绿色发展 · 低碳制造', '自 2014 年起持续推动绿色工艺改造与节能降耗，多项成果获省级环境创新奖项；持续开展碳核查与碳足迹认证，助力"双碳"目标。'],
        ['责任治理 · ESG', '建立并完善质量、环境、职业健康安全、信息安全管理体系，每年发布 ESG 报告，系统披露环境、社会及治理实践与绩效。'],
        ['公益与员工关怀', '设立“西力科技专项慈善基金”，截至 2025 年底累计资助 55 位患者、发放善款 22.54 万元；助推脱贫攻坚成果、帮扶青川产业发展；已连续七年组织员工参与无偿献血活动。'],
      ],
      officialAction: '西力科技官方网站',
      officialUrl: 'https://www.cnxili.com/en/WestForceProfile/index.aspx',
    },
    news: {
      title: '新闻动态',
      heroTitle: '新闻与里程碑。',
      heroBody: '公司公告与塑造西力的重要节点——故事仍在继续，此页持续更新。',
      items: [
        ['2026', '中标喜讯', '国家电网中标金额超 1.62 亿元', '西力中标国家电网 2026 年营销项目第一次计量设备招标——A 级单相、B/C 级三相智能电能表、智能融合终端与计量用互感器，中标总额约 1.62 亿元；并相继中标国网湖北、安徽、黑龙江与上海项目。', 'meter-line'],
        ['2026', 'ESG', '发布 2025 年度 ESG 报告', '杭州西力与浙江西力分别发布 2025 年度环境、社会及治理报告，信息披露覆盖计量与新能源两大业务板块。', 'pv-solution'],
        ['2026', '经营业绩', '2025 年度业绩稳健，分红 5288 万元', '2025 年营业收入 5.66 亿元，归母净利润 1.04 亿元，经营性现金流增长 53%。每 10 股派现 3 元，分红占净利润 50.9%。', 'zhuantang-hq'],
        ['2026', '智能制造', '“未来工厂”技改入选浙江省示范项目', '智能能源计量终端未来工厂技改项目入选浙江省 2026 年度生产制造方式转型示范项目计划。', 'robot-cell'],
        ['2026', '荣誉', '获评国家级绿色低碳工厂', '西力科技获评"国家级绿色低碳工厂"，节能低碳的智能制造体系再获国家级认可。', 'deqing-park'],
        ['2025', '里程碑', 'AI 与制造深度融合入选国家级典型案例', '西力 AI 与制造深度融合入选省级、国家级典型案例；西力新能源销售收入同比增长 281%。', 'robot-glow'],
        ['2024', '经营业绩', '全年净利润 1.04 亿元创历史新高', '全年净利润达 1.04 亿元，创历史新高；数字化运营平台上线，实现可视化、数字化管理。', 'hall'],
        ['2023', '智能制造', '德清智能化产业园全面投产', '12 万平方米产业园全面投产，数字化车间、智能立库投用。', 'campus-aerial'],
        ['2021', '里程碑', '西力科技登陆科创板', '杭州西力智能科技（688616.SH）在上海证券交易所科创板上市——对精准工程的公开承诺。', 'listing-2021'],
        ['2005', '智能制造', '数字化工厂之路启程', '西力将产品生命周期、制造执行与设备数据汇成一个闭环——质量靠测量验证，而非假设。', 'factory-2005'],
        ['1968', '行业积淀', '电能计量积淀开启', '深耕电能计量的行业根基，至今仍支撑着西力的精度文化。', 'heritage-1968'],
      ],
      note: '更多公告将在官方核实后发布。',
    },
    careers: {
      title: '加入我们',
      heroTitle: '打造电网信赖的仪器。',
      heroBody: '精准的工作需要精准的人。加入一支把计量当作工艺、把能源当作使命的团队。',
      whyTitle: '为什么选择西力',
      why: [
        ['真实的基础设施', '你的作品进入电网、工厂与家庭——以数十年计，而非以冲刺计。'],
        ['工程深度', '计量、电力电子、通信与制造系统同在一个屋檐下。'],
        ['上市平台', '科创板上市公司的稳定，专精企业的专注。'],
      ],
      areasTitle: '招聘方向',
      areas: [
        ['研发工程', '计量、储能、嵌入式与通信工程。'],
        ['制造与供应链', '数字化工厂运营、工艺与设备工程。'],
        ['质量与检测', '从产线到实验室的计量级验证。'],
        ['市场与销售', '电网项目与国际市场拓展。'],
      ],
      action: '自我介绍',
      note: '发送简历并注明感兴趣的方向——每一份认真的申请我们都会回复。',
    },
    contact: {
      title: '联系我们',
      heroTitle: '让能源更加清晰可读。',
      heroBody: '告诉我们您的能源系统在哪些方面需要更高的精准度、可视化与可靠性。',
      action: '开始交流',
      channelsTitle: '联系方式',
      email: 'hzxilidb@cnxili.com',
      offices: '杭州 · 德清 · 中国',
      officeTitle: '办公地点',
      locations: [
        ['zhuantang-hq', '公司总部 · 杭州', '浙江省杭州市西湖区转塘街道良浮路 173 号，邮编 310024 · 0571-87825461 / 56660360'],
        ['deqing-park', '生产基地 · 德清', '浙江省湖州市德清县环城北路 733 号，邮编 313000 · 0572-8233298 / 8233258'],
      ],
      emailTitle: '电子邮箱',
      responseNote: '方案类咨询将在两个工作日内回复。',
    },
    footer: {
      descriptor: '智慧能源',
      colProducts: '产品体系',
      colSolutions: '解决方案',
      colCompany: '公司',
      legal: '© 2026 西力科技 版权所有',
    },
  },
}
